docs/design/design.md

This document describes the functions of kubeadm and how the phases should be splitted up
@lukemarsden @roberthbailey @mikedanese @errordeveloper @pires @dmmcquay @jbeda

Add a doc about the kubeadm design and phases implementation

---

docs/test-failures.md

Fixes #251. 
@luxas suggested this might also be submitted to kubernetes/community. Before doing so, do folks think that 
1. this doc can be abstracted,
2. it's relevant enough to other SIGs?

Add triage doc

---

docs/design/design_v1.7.md
docs/design/design_v1.8.md

**What this PR does / why we need it:**
Update design doc with 1.8 features/changes
**Special notes for your reviewer:**
Still in progress, but shared to start gathering feedbacks/contributions
Below task for this PR; please let me know if something is missing:
kubeadm first level to be documented / reviewed for 1.8 
kubeadm init phases to be documented / reviewed for 1.8
kubeadm join phases to be documented / reviewed for 1.8
Others topics to be documented / reviewed for 1.8 ...

Update design doc with 1.8 features/changes

---

docs/design/design_v1.7.md
docs/design/design_v1.8.md

Fix broken links for the design doc of bootstrap discovery in design doc of kubeadm v1.7 v1.8
Signed-off-by: Ziqi Zhao <zhaoziqi@qiniu.com>

Fix broken links for the design doc of bootstrap discovery.

---

tests/e2e/pinned_releases.sh

Fixes #264. Based on @krzyzacy's feedback, we should create a basic bash script that verifies there are matching kubeadm debs for kubernetes releases.
The next steps after this are:
1. add new prow jobs to test-infra that run this script from this repo
2. add other linux distros (using `yum list` or something)
Running this on ubuntu, this is the output:
```
Skipped these versions:
v1.5.8
These versions do not have matching debs:
v1.6.12 v1.7.9 v1.6.10 v1.6.9 v1.6.8
```
Should we have debs for those releases? 
/cc @luxas @timothysc @krzyzacy

Add script for testing pinned releases

---

docs/design/design_v1.9.md

fixes #563 Update design doc for v1.9
Nb. this document will be moved into the official kubernetes.io docs after reshuffle of kubeadm reference doc will merge (https://github.com/kubernetes/website/pull/6103)

design1.9-update

---

docs/design/design_v1.10.md

This contains two changes split into two commits (we can separate into two PRs if desired):
- Update to reflect changes made in kubernetes/kubernetes#57287
- Consistency and grammar fixes throughout the entire document:
- Trim trailing whitespace
- Change `[Error]` to `[error]` to be consistent everywhere
- Fix grammar for things like `does not exists` which should be `does not exist`

Update v1.10 design doc preflight check description and fix consistency/grammar

---

docs/design/design_v1.8.md

See https://github.com/kubernetes/kubeadm/issues/616
This uses the specifically versioned logo for the 1.8 design.

Add Certified k8s Logo to v1.8 design doc

---

OWNERS

This file now includes all users in k8s.io/kubernetes/cmd/kubeadm/OWNERS.
I wasn't sure if I should leave `errordeveloper` as that user does not currently exist in the [core repo OWNERS file](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/OWNERS). Should I remove them here, or update the core OWNERS file to include them?
Closes #632.

Update OWNERS to merge in core k8s repo kubeadm OWNERS

---

docs/design/design_v1.9.md

See #616
This uses the specifically versioned logo for the 1.8 design.

Add Certified k8s Logo to v1.9 design doc

---

README.md

The README.md references v1.6.  That's out of date and this represents an
unnecessary maintenance point.  Simply refer to the milestones page.
Signed-off-by: Tim Pepper <tpepper@vmware.com>

readme: update stale info

---

docs/design/design_v1.7.md
docs/design/design_v1.8.md
docs/design/design_v1.9.md

There are a two primary ways to extend `kubeadm`:
a two->two
does not exists->does not exist
does not contains->does not contain

Some small typo fixes

---

CONTRIBUTING.md
vagrant/.gitignore
vagrant/README.md
vagrant/Vagrantfile
vagrant/copy_kubeadm_bin.sh

We discussed on last week's kubeadm call, that we would like move this
repo into the kubeadm contributor repo, so we improve our shared tooling
and contributor experience.
This vagrant environment has been shown to aide in developer ramp up for
new contributors.
The documentation fixes provide a happier path to discovering how to
build the software.
approved by @timothysc
Fixes: https://github.com/stealthybox/vagrant-kubeadm-testing/issues/1

Merge vagrant-kubeadm-testing for contributor experience

---

vagrant/hack/lib/ansible-utils.rb
vagrant/hack/lib/cluster-api.rb
vagrant/hack/lib/kubeadm-options.rb
vagrant/hack/lib/kubernetes-utils.rb
vagrant/hack/lib/test-guide.rb
vagrant/hack/lib/utils.rb
vagrant/hack/lib/vagrant-utils.rb

This PR implements the second part of https://github.com/kubernetes/kubeadm/pull/795 (2 of 3), that consists of a set of scripts that are responsible for parsing the cluster API spec and translates it into something that can be used by Vagrant and by the ansible provisioner.
NB. the test guide is only drafted, and it is intended to be improved over time ;-)
/CC @timothysc @luxas @stealthybox @liztio @detiber @chuckha

kubeadm-contrib-hack-lib

---

CONTRIBUTING.md
testing-pre-releases.md

This PR documents how to test pre-release versions of Kubernetes with kubeadm; which version numbers I should take care of, where to retrieve pre-compiled artefacts, how to build locally.
/CC @kubernetes/sig-cluster-lifecycle-pr-reviews 
This PR is part of #849 checklist

testing-pre-releases

---

vagrant/hack/ansible/roles/common/tasks/main.yml

`kubeadm` fails with swap on https://github.com/kubernetes/kubernetes/pull/31996
Added tasks to disable swap in all nodes from https://github.com/kubernetes/contrib/blob/master/ansible/roles/node/tasks/swapoff.yml

Disable swap in all nodes

---

docs/design/design_v1.10.md
docs/design/design_v1.8.md
docs/design/design_v1.9.md

fix a typo: goes trough-> goes through

Typo fix: trough->through

---

tests/e2e/README.md
tests/e2e/packages/README.md
tests/e2e/packages/verify_packages_published.sh

also:
- update the test README to reflect the folder change.
- add a README in e2e/tests explaining that this folder
contains e2e tests and have some links in there.
- do some minor whitespace / comment cleanup in the .sh
my idea here is to have folders under e2e that specify e2e type.
(having this as early as possible is better!)
tests/e2e/packages is what would be available now.
tests/e2e/manifests is what's coming soon.
test-infra PR on hold here:
https://github.com/kubernetes/test-infra/pull/9565

move verify_packages_published to it's own folder

---

docs/managing-e2e-tests.md

as per the discussion in slack with @timothysc, old x-on-y jobs should be removed too, while old upgrade jobs should be left.
this PR amends the e2e doc.
/kind cleanup
/assign @timothysc 
edit: PR for test-infra will follow.

e2e-docs: instruct about removing old x-on-y jobs

---

vagrant/hack/lib/help_utils.py

Line 52&75: does not requires->does not require

Fix grammar errors in some warning messages in help_utils.py

---

tests/e2e/manifests/README.md
tests/e2e/manifests/verify_manifest_lists.go
tests/e2e/manifests/verify_manifest_lists.sh
tests/e2e/manifests/verify_manifest_lists_test.go

this PR adds an e2e test for verifying the manifests lists.
on top of `verify_manifest_lists.go` there are some details on how this works.
QUESTION: this basically traverses manifest lists json files until it reaches the image layers.
currently download of the layers is skipped and only the `Content-Length` of their headers is verified.
these can end up being quite large, so should the full download of all layers be enabled? (the toggle is called `downloadLayers`).
test-infra PR to follow.
/hold
/assign @timothysc 
/cc @dims @BenTheElder @ixdy @Random-Liu

add an e2e test for verifying manifest lists

---

docs/design/design_v1.10.md
docs/design/design_v1.8.md
docs/design/design_v1.9.md

In these article, "api server" and "API server" are not consistent. For example, in [docs/design/design_v1.9.md](https://github.com/kubernetes/kubeadm/compare/master...JoeWrightss:patch-1?expand=1#diff-21ece680a29b03664c2e243e1b7cbf37), "api server" has only appear once, but others are "API server", please keep them consistent.

Fix some typos

---

tests/e2e/kind/single-cp/single-cp.yaml
tests/e2e/kind/test-cmd-basic.sh

Add a "basic" test-cmd script to be used from the
kind deployer.
Also include a single-cp config for kind.
Mostly experimenting at this point.
The directory structure is a subject to change
once more test cases are added.
test-infra job PR is here: TODO

kind: add simple test-cmd script and single-cp config

---

kinder/README.md
kinder/roadmap.md

kinder is an example of [kind](https://github.com/kubernetes-sigs/kind) used as a library, designed for simplifying kubeadm development/local testing
This PR introduces the kinder roadmap/readme file, for collecting the first round of feedback about goals/high-level features before adding the actual kinder code
/assign @timothysc 
/assign @BenTheElder 
/assign @neolit123 

Welcome kinder!

---

OWNERS

**What type of PR is this?**
/kind cleanup
**What this PR does / why we need it**:
Align OWNER file to what we have in K/K. More specifically
- Graduates @rosti to approver (and reviewer) 🎉
- Adds @ereslibre @yagonobre as reviewers 🎉
- Removes @stealthybox & @xiangpengzhao 👋
Thanks for your contributions, and hopefully we'll see you
around again @stealthybox & @xiangpengzhao!
Congrats new reviewers and approvers!
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
/sig cluster-lifecycle
/area kubeadm
@kubernetes/sig-cluster-lifecycle
/assign @luxas @timothysc @fabriziopandini @neolit123

Update kubeadm OWNERS file

---

CONTRIBUTING.md

This links the "Building" section of CONTRIBUTING.md to /kinder/README.md .
Related issue: #1466

Update CONTRIBUTING doc link to kinder README

---

kinder/cmd/kinder/get/artifacts/artifacts.go
kinder/cmd/kinder/get/get.go
kinder/cmd/kinder/kinder.go
kinder/doc/prepare-for-tests.md
kinder/go.mod
kinder/go.sum
kinder/pkg/extract/extract.go

This PR adds the new `kinder get artifacts` that allows to retrive Kubernetes build artifacts from different sources
This is a useful feature and also an initial step for implementing kinder build node-variant from build artifacts, that is a piece of the puzzle for getting E2E tests on kubeadm upgrades
/kind feature

add kinder get artifacts command

---

kinder/cmd/kinder/kinder.go
kinder/cmd/kinder/test/e2e/e2e.go
kinder/cmd/kinder/test/e2ekubeadm/e2ekubeadm.go
kinder/cmd/kinder/test/test.go
kinder/pkg/test/binary.go
kinder/pkg/test/e2e.go
kinder/pkg/test/flags.go

This PR implements `kinder test e2e` and `kinder test e2e-kubeadm` commands
NB. There are few TODO in the code, but this should be enough to get started with the kubeadm upgrade tests
/kind feature

Add kinder e2e command

---

kinder/doc/e2e-test.md
kinder/doc/getting-started.md
kinder/doc/reference.md
kinder/doc/test-HA.md
kinder/doc/test-XonY.md
kinder/doc/test-upgrades.md
kinder/roadmap.md

This PR updates kinder docs with changes in https://github.com/kubernetes/kubeadm/pull/1491

Update kinder docs for e2e support

---

kinder/README.md
kinder/doc/prepare-for-tests.md
kinder/doc/reference.md
kinder/doc/test-XonY.md
kinder/doc/test-upgrades.md
kinder/roadmap.md

This PR updates kinder docs with changes in https://github.com/kubernetes/kubeadm/pull/1488

update kinder docs

---

kinder/cmd/kinder/do/do.go
kinder/cmd/kinder/test/e2e/e2e.go
kinder/cmd/kinder/test/e2ekubeadm/e2ekubeadm.go
kinder/hack/ci/workflows/upgrade-stable-to-master.yml
kinder/pkg/actions/kubeadm-init.go
kinder/pkg/actions/kubeadm-join.go
kinder/pkg/actions/kubeadm-upgrade.go
kinder/pkg/actions/util.go
kinder/pkg/actions/waiter.go
kinder/pkg/cluster/context.go
kinder/pkg/test/workflow/workflow.go

This PR implements a waiter that blocks kinder actions waiting for nodes to get ready, pods to restart or to get upgraded etc. with the ultimate goal to make test workflows more stable and avoid flakes
It includes also a few small improvements to the test workflow manager (in a separated commit)
/kind feature

Add waiter to kinder

---

kinder/ci/kinder-run.sh

Temporary enable verbose log to better understand test infra error
/kind feature

Enable verbose log for kinder test

---

kinder/pkg/actions/waiter.go

Fix wait duration to nanoseconds (!) to milliseconds

fix wait duration

---

kinder/pkg/extract/extract.go
kinder/pkg/test/workflow/taskCmdBuilder.go

This PR implements add support for template funcs to kubeadm test workflow yaml format.
In this initial release, it supports only one func, `resolve`, that resolve release labels. example of usage (with two different syntaxes):
```yaml
vars:
stable: '{{ resolve "release/stable" }}'
latest: '{{ "ci/latest" | resolve }}'
```
/kind feature

Add support for template funcs to kubeadm test workflow

---

kinder/.gitignore
kinder/pkg/test/workflow/workflow.go

```
kinder-workflow: propagate errors to the parent workflow command  …
Even if exitOnError is false, make sure that an error is returned
from the Workflow::Run() function, so that the workflow command's
RunE function causes the process to exit with a non-zero status.
This is done using the foundError flag.
Also always return the causing error instead of nil.
```
```
kinder: ignore kinder-test-workflow* paths in .gitignore  …
This is done so that execution of the kinder command from the
kinder source directory ignores the paths where kinder writes the
logs.
```
/kind cleanup

kinder-workflow: propagate errors to the parent workflow command

---

kinder/pkg/test/workflow/taskCmdRunner.go
kinder/pkg/test/workflow/workflow.go

Fix junit-runner.xml serialization and log file name to get everything sorted properly when navigating the artifact folder

fix junit-runner.xml

---

kinder/ci/workflows/upgrade-stable-master.yaml

The upgrade-stable-master.yaml uses a non-default
name for the cluster (kinder-test). Use this name
for all `do` commands.
Long term we can try overriding the default name "kind"
from kinder.
/kind bug

kinder: use the --name flag for all commands

---

kinder/ci/workflows/upgrade-stable-master.yaml

- move e2e test before upgrade
- add cluster-info test before and after upgrade
/kind failing-test

kinder: temporary modify the upgrade job to test e2e before upgrade

---

kinder/cmd/kinder/test/e2e/e2e.go

/kind failing-test
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-stable-master/1120750640776089603

kinder: temporary skip the aggregated apiserver conformance test

---

kinder/ci/workflows/upgrade-stable-master.yaml

Also move the --name flag of the "get logs" step.
/kind failing-test

kinder: move the e2e step after upgrade

---

kinder/pkg/actions/util.go

We should consider how we track this going forward.
With every release of calico the url will change.
A potential solution is to track github.io/kube-flannel.yaml instead as
there are fewer moving parts and it will track master in the flannel
repo.
Signed-off-by: Duffie Cooley <dcooley@heptio.com>

kinder: update calico manifest to latest stable

---

kinder/cmd/kinder/build/nodevariant/nodevariant.go
kinder/doc/prepare-for-tests.md
kinder/doc/reference.md
kinder/pkg/build/alter/alter.go
kinder/pkg/build/alter/initBits.go
kinder/pkg/build/alter/upgradeBits.go

This PR adds a new `--with-init-artifacts` flag to `kinder build node-variant` command
NB. this is a temporary replacement for `kind build node-image --type=tar` that seems blocked (see https://github.com/kubernetes-sigs/kind/pull/396)

Add --with-init-artifacts flag to kinder build node-variant command

---

kinder/doc/e2e-test.md
kinder/doc/prepare-for-tests.md
kinder/doc/test-XonY.md
kinder/doc/test-upgrades.md

Several docs inside the `doc/` folder are using `doc/reference.md` leading in broken links

Fix broken links to Kinder reference docs

---

kinder/ci/workflows/upgrade-stable-master.yaml
kinder/pkg/test/workflow/taskCmdRunner.go
kinder/pkg/test/workflow/workflow.go

This PR adds support for setting tasks to ignore errors
This allows to makes test pass if kind get logs flakes but everything else pass

kinder: task ignoreError

---

OWNERS

The label is not needed for this repository as the
repository implies that this PR or ticket is already related
to kubeadm.
Having the label causes errors in the "owners-label" plugin:
fixes https://github.com/kubernetes/kubeadm/issues/1547

OWNERS: remove redundant area/kubeadm label

---

kinder/doc/getting-started.md

Fix typo in getting started guide for single node. 
The create cluster command should be:
```
kinder create cluster --image kindest/node:vX --worker-nodes 0
``` 
**Instead of** 
```
kinder create cluster --image kindest/node:vX --workers-nodes 0
```

Fix typo in create cluster command

---

kinder/cmd/kinder/create/cluster/createcluster_test.go

This PR adds a set of unit test for checking that kinder uses the right kubeadm config version and also applies the patches for the supported config variants when requested
NB. this should provide a good signal on kinder/usage of kubeadm config versions, without the need for implementing a pool of presubmit test (it is a partial replacement of https://github.com/kubernetes/kubeadm/pull/1550)
/kind test

kinder: add unit tests for kubeadm config versions

---

kinder/ci/workflows/skew-1.14-on-1.13.yaml
kinder/ci/workflows/skew-master-on-stable.yaml
kinder/ci/workflows/skew-x-on-y-tasks.yaml
kinder/ci/workflows/upgrade-1.13-1.14.yaml
kinder/ci/workflows/upgrade-stable-master.yaml
kinder/ci/workflows/upgrade-tasks.yaml

This PR:
- change upgrade-stable-master job and upgrade-1.13-1.4 to test HA + automatic copy certificates
- change master-on-stable job and 1.14 on 1.13 to test HA + automatic copy certificates
rif https://github.com/kubernetes/kubeadm/issues/1567
NB. In case I'm out of sync with other helping to this effort, feel free to close.
/kind test
/assign @neolit123 

kinder make upgrade and skew e2e tests HA ready

---

kinder/ci/workflows/skew-1.14-on-1.13.yaml
kinder/ci/workflows/skew-master-on-stable.yaml
kinder/ci/workflows/upgrade-1.13-1.14.yaml
kinder/ci/workflows/upgrade-stable-master.yaml

As per comment in https://github.com/kubernetes/kubeadm/pull/1580, make E2E jobs for HA create 3 control-plane nodes
/kind test

make HA test create 3 control-plane nodes

---

kinder/cmd/kinder/create/cluster/createcluster.go
kinder/pkg/cluster/kubeadmconfig.go

With this PR kinder can automatically detect initVersion from official kind node images, and use this to select the right kubeadm config version
/kind feature

kinder: initVersion improved detection

---

kinder/pkg/actions/kubeadm-init.go
kinder/pkg/actions/kubeadm-join.go
kinder/pkg/actions/kubeadm-upgrade.go

Implements the first set of changes for considering CLI changes introduced in v1.15
Nb. change for `--certificate-key` that can't anymore be combined with `--config` is not included
/kind feature

kinder: v1.15 CLI changes

---

kinder/cmd/kinder/create/cluster/createcluster_test.go
kinder/pkg/actions/kubeadm-init.go
kinder/pkg/cluster/kubeadmconfig.go

This PR implements a workaround for using kinder to test v1beta2 kubeadm config version, even if kind does not support this yet.
It also adapts the init workflow to pass the `certificate-key` using the config file instead of the flag
/kind feature
/assign @rosti

kinder: v1beta2 workaround

---

kinder/ci/kubeadm-periodic.tests.md
kinder/ci/workflows/ha-cert-copy-with-external-etcd-1.14.yaml
kinder/ci/workflows/ha-cert-copy-with-external-etcd-master.yaml
kinder/ci/workflows/ha-cert-copy-with-external-etcd.yaml

Create two new workflows to deploy an HA cluster with secret copy and external etcd.
`test-infra` related change: https://github.com/kubernetes/test-infra/compare/master...ereslibre:ha-kubeadm-kinder, will submit a PR there when this one merges.

Add workflow for HA cert copy with external etcd

---

kinder/pkg/actions/kubeadm-upgrade.go

This PR fixes image preload for kubeadm upgrades, making the kube-proxy image available also on worker nodes.
/kind bug

kinder: fix-image-preload

---

kinder/ci/kubeadm-periodic.tests.md
kinder/ci/workflows/external-etcd-1.14.yaml
kinder/ci/workflows/external-etcd-master.yaml
kinder/ci/workflows/external-etcd.yaml

Also, improve the kubeadm periodic tests documentation to explicitly
mention that those jobs use `ci/latest` and `ci/latest-1.14`.

Rename `ha-cert-copy-with-external-etcd` to `external-etcd`

---

kinder/cmd/kinder/create/cluster/createcluster.go
kinder/pkg/cluster/etcd.go

When an external etcd node is created, ideally it needs the
etcd version that kubeadm "ships".
To be able to obtain the etcd version (image tag):
- Create a temporary node-image
- Exec "kubeadm config image list | grep etcd" to obtain etcd image:tag
- Remove the temporary node-image
- Pre-pull the etcd image:tag if needed.
should fix failing jobs:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-external-etcd-master
and
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-external-etcd-1.14
```
Creating external etcd for the cluster "kinder-external-etcd" ...
Error: failed to create cluster: failed to create external etcd container: failed to get container id, output did not match: [Unable to find image 'k8s.gcr.io/etcd:3.2.24' locally …
```

kinder: obtain the etcd version from the node-image

---

kinder/pkg/actions/util.go

This change is required since the 3.8 manifest moves to using
apps/v1 instead of extensions/v1beta1 for types like DaemonSet
and Deployment.
See PR 70672 of k/k.
failing tests:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-external-etcd-master

kinder: update calico to the latest version 3.8

---

kinder/ci/workflows/external-etcd.yaml
kinder/pkg/cluster/etcd.go

In etcd.go when we try to get the propper version of etcd
to use from "kubeadm config images list", if the version
of kubeadm is much older than "stable-1" (which is the default label
in kubeadm), the ouput shows a warning to stderr e.g.:
```
I0626 02:54:47.931193    3673 version.go:240] remote version
is much newer: v1.15.0; falling back to: stable-1.14
```
For some reason this output becomes part of the "etcdVersionBuf"
which is supposed to only contain stdout (cmd.SetStdout(&etcdVersionBuf)).
Omit this ouput by piping stderr to /dev/null and only
catch the etcd image string - e.g.:
```
k8s.gcr.io/etcd:3.3.10
```
Once kubeadm supports machine readable output we can parse
this output properly without workarounds.
-----
fixes failures for the external etcd 1.14 test: …

kinder: avoid polution of the output of "kubeadm config images list"

---

OWNERS

- comment out Chuck and Liz
- add SataQiu as reviewer
- add ereslibre as approver
xref https://github.com/kubernetes/kubernetes/pull/79218
@kubernetes/sig-cluster-lifecycle-pr-reviews 
/hold
/assign @luxas @timothysc @fabriziopandini 
/kind cleanup
/priority important-soon
cc @chuckha @liztio

update OWNERS for 1.16

---

kinder/hack/verify-all.sh
kinder/hack/verify-boilerplate.go
kinder/hack/verify-boilerplate.sh
kinder/hack/verify-boilerplate_test.go

already used in /hack under:
- cluster-api-provider-docker
- cluster-api-bootstrap-provider-kubeadm

kinder: include tooling for boilerplate verification

---

kinder/cmd/kinder/do/do.go
kinder/pkg/cluster/manager/actions/actions.go
kinder/pkg/cluster/manager/actions/kubeadm-init.go
kinder/pkg/cluster/manager/actions/kubeadm-join.go
kinder/pkg/cluster/manager/actions/kubeadm-reset.go
kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go
kinder/pkg/cluster/status/node.go

This PR adds a `-v` flag to the `kinder do` command; this flag is forwarded to all the kubeadm command thus allowing to increase the verbosity of logs for E2E tests 

add -v flag to kinder do command

---

kinder/pkg/build/alter/alter.go
kinder/pkg/build/bits/binaryBits.go
kinder/pkg/build/bits/imageBits.go
kinder/pkg/build/bits/initBits.go
kinder/pkg/build/bits/installer.go
kinder/pkg/build/bits/upgradeBits.go
kinder/pkg/cluster/manager/actions/images.go
kinder/pkg/cluster/manager/actions/kubeadm-init.go
kinder/pkg/cluster/manager/actions/kubeadm-join.go
kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go
kinder/pkg/cri/actionhelper.go
kinder/pkg/cri/containerd/actionhelper.go
kinder/pkg/cri/docker/actionhelper.go
kinder/pkg/extract/extract.go

This PR fixes the E2E tests failing after https://github.com/kubernetes/kubernetes/pull/80047 merged
The PR has two commits:
- `fix-image-tar that` introduces the actual fix, adjusting the image name with `-amd64` suffix during the alter image process
- `add check prepulled images` that introduces a new check before main kubeadm commands; the check compares the images kubeadm is going to use with the images already existing on the node and reports what is missing. In normal conditions, the output should be something similar to:
```
kinder-upgrade-control-plane2:$ Checking pre-loaded images
Some of the required images are not pre-loaded into the container runtime:
k8s.gcr.io/pause:3.1
k8s.gcr.io/etcd:3.3.10
k8s.gcr.io/coredns:1.3.1
```
if also the control plane images are missing, this is …

Fix image preload

---

CONTRIBUTING.md

This PR improves kubeadm contributing guidelines by adding info about the expected usage of the  `lifecycle/active` label, with the intent to avoid potential conflicting PRs on the same issue
/assign @neolit123 
/assign @rosti

improve-contributing

---

kinder/ci/workflows/external-etcd.yaml
kinder/ci/workflows/skew-1.15-on-1.14.yaml
kinder/ci/workflows/skew-master-on-1.15.yaml
kinder/ci/workflows/skew-x-on-y-tasks.yaml
kinder/ci/workflows/upgrade-1.14-1.15.yaml
kinder/ci/workflows/upgrade-1.15-master.yaml
kinder/ci/workflows/upgrade-tasks.yaml
kinder/cmd/kinder/build/nodevariant/nodevariant.go
kinder/cmd/kinder/create/cluster/createcluster.go
kinder/pkg/build/alter/alter.go
kinder/pkg/cluster/manager/actions/kubeadm-config.go
kinder/pkg/cluster/manager/create.go
kinder/pkg/cluster/status/cri.go
kinder/pkg/cluster/status/node.go
kinder/pkg/cri/alterhelper.go

This PR implements autodetection for the CRI runtime installed into base/node images. As a consequence, the temporary `--cri` flag is removed

Kinder: CRI autodetection

---

kinder/ci/workflows/external-etcd.yaml
kinder/ci/workflows/skew-1.15-on-1.14.yaml
kinder/ci/workflows/skew-master-on-1.15.yaml
kinder/ci/workflows/upgrade-1.15-master.yaml
kinder/cmd/kinder/create/cluster/createcluster.go
kinder/pkg/cluster/manager/actions/actions.go
kinder/pkg/cluster/manager/actions/kubeadm-config.go
kinder/pkg/cluster/manager/actions/kubeadm-init.go
kinder/pkg/cluster/manager/actions/kubeadm-join.go
kinder/pkg/cluster/manager/actions/loadbalancer.go
kinder/pkg/cluster/manager/create.go

This PR remove calls to `kubeadm-config` and `loadbalancer` actions during `kinder create`; instead those actions will be automatically executed before `kubeadm init/join` on per-node basis.
This change resulted in cleaner the UX for `kinder create` and, most importantly, it enables joining node with different discovery modes on the same cluster

Remove automatic execution of actions during kinder create

---

kinder/hack/verify-gofmt.sh

the kubeadm bootsrap provider found a minor bug in your verify-gofmt.sh.
the file in kinder needs a fix too.
https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/72

kinder: fix minor bugs in verify-gofmt.sh

---

kinder/cmd/kinder/create/create.go

I found the help text a little confusing, this command cannot add (that I could figure out) a new node into an existing kind cluster. If we did want to support this I think it would be better suited with an `add-node` command anyhow. What do you think? @fabriziopandini

updated confusing command help text

---

kinder/pkg/test/e2e/runner.go

Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>

fix misspelled words in runner.go

---

kinder/ci/kubeadm-periodic.tests.md
kinder/ci/workflows/kustomize-master.yaml
kinder/cmd/kinder/do/do.go
kinder/cmd/kinder/exec/exec.go
kinder/pkg/cluster/manager/actions/actions.go
kinder/pkg/cluster/manager/actions/copy-certs.go
kinder/pkg/cluster/manager/actions/kubeadm-config.go
kinder/pkg/cluster/manager/actions/kubeadm-init.go
kinder/pkg/cluster/manager/actions/kubeadm-join.go
kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go
kinder/pkg/cluster/manager/actions/waiter.go
kinder/pkg/constants/constants.go

This PR implements the required changes in order to use kinder for testing kubeadm-kustomize feature

Kinder: add support for testing kubeadm-kustomize

---

kinder/pkg/test/e2e/runner.go

fix mis-spelling in runner.go

---

kinder/cmd/kinder/get/artifacts/artifacts.go
kinder/hack/verify-all.sh
kinder/hack/verify-staticcheck.sh
kinder/pkg/cluster/manager/manage.go
kinder/pkg/cluster/status/node.go
kinder/pkg/cri/containerd/actionhelper.go
kinder/pkg/cri/docker/actionhelper.go
kinder/pkg/test/workflow/workflow.go

Enable static checks for .go files which was recently enabled in
the kubernetes/kubernetes repository too.
/kind feature cleanup

kinder: add hack/verify-staticcheck.sh

---

kinder/ci/workflows/external-etcd-1.16.yaml
kinder/ci/workflows/skew-1.16-on-1.15.yaml
kinder/ci/workflows/skew-master-on-1.16.yaml
kinder/ci/workflows/skew-x-on-y-tasks-automatic-copy-certs.yaml
kinder/ci/workflows/skew-x-on-y-tasks.yaml
kinder/ci/workflows/upgrade-1.12-1.13.yaml
kinder/ci/workflows/upgrade-1.13-1.14.yaml
kinder/ci/workflows/upgrade-1.15-1.16.yaml
kinder/ci/workflows/upgrade-1.16-master.yaml
kinder/ci/workflows/upgrade-tasks-automatic-copy-certs.yaml

- for skew jobs import the new skew-x-on-y-tasks-automatic-copy-certs.yaml
(this can be renamed once our entire skew supports copy certs)
- do the same for upgrade jobs
- use ci/latest-x as upgrade targets instead of ci/release-x!
test infra PR https://github.com/kubernetes/test-infra/pull/14037
/hold

kinder: add 1.16 jobs

---

kinder/pkg/cluster/manager/actions/kubeadm-init.go

/kind bug
/area kinder
After performing `kinder do kubeadm-init` on a cluster with worker nodes,
the calico-node pods on the worker nodes will CrashLoop.
This is because this `rp_filter` sysctl is only set on the control-plane nodes.
I'm changing this to all nodes, because there is no compelling reason for any external-load-balancer or other cluster-infrastructure to have a different kernel-routing setup than the k8s nodes.
I'd also be fine to move this to the end of `createNodes()` if that is preferred.

Set calico `rp_filter` sysctl for all nodes (including load-balancer)

---

tests/e2e/manifests/verify_manifest_lists.go
tests/e2e/manifests/verify_manifest_lists.sh

xref https://github.com/kubernetes/kubernetes/pull/81029/files
The CCM image was removed for the release of 1.16.
Skip checking this image for versions 1.16*.
Also use go modules for running the test using the shell script, which makes things much faster if e.g. once has the apimachinery module locally already.

verify_manifest_lists: skip cloud-controller-manager for 1.16

---

kinder/pkg/cluster/manager/actions/kubeadm-init.go

This should fix the external-etcd CI breakage introduced by #1760
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-external-etcd-master
Also, this surprised me -- `kinder exec @all` isn't the same as `AllNodes()`:
```
kinder exec --name=kinder-upgrade @all -- sysctl -w net.ipv4.conf.all.rp_filter=1
🚀 Executing command on node kinder-upgrade-control-plane 🚀
net.ipv4.conf.all.rp_filter = 1
🚀 Executing command on node kinder-upgrade-control-plane2 🚀
net.ipv4.conf.all.rp_filter = 1
🚀 Executing command on node kinder-upgrade-control-plane3 🚀
net.ipv4.conf.all.rp_filter = 1
🚀 Executing command on node kinder-upgrade-worker 🚀
net.ipv4.conf.all.rp_filter = 1
🚀 Executing command on node kinder-upgrade-worker2 🚀
net.ipv4.conf.all.rp_filter = 1
kinder exec …
```

Set rp_filter sysctl on k8s nodes only -- etcd has readOnly fs

---

docs/managing-e2e-tests.md

- Provide some instructions for updating kinder workflows.
- Reorganize the sections a little: introduction, configurations,
how-to do updates, more info
- Add information on using prow-job annotations and remove
the old way of using testgrid config entries.
fixes https://github.com/kubernetes/kubeadm/issues/1695

managing-e2e-tests: refactor the document

---

kinder/ci/workflows/upgrade-1.12-1.13.yaml
kinder/ci/workflows/upgrade-tasks.yaml

this PR fix failingE2E test upgrade-1-12-1-13 
error: "unable to add a new control plane instance on a cluster that doesn't use an external etcd"

fix E2E test upgrade-1-12-1-13

---

kinder/cmd/kinder/build/baseimage/baseimage.go
kinder/cmd/kinder/build/build.go
kinder/cmd/kinder/build/build/TODO.md
kinder/doc/kind-kinder.md
kinder/images/base/docker/Dockerfile
kinder/images/base/docker/README.md
kinder/images/base/docker/clean-install
kinder/images/base/docker/entrypoint/main.go
kinder/pkg/build/base/README.md
kinder/pkg/build/base/base.go

This PR adds in kinder support for building docker base-image
xref: https://github.com/kubernetes/kubeadm/issues/1759

kinder: support for building docker base-image

---

kinder/ci/kubeadm-periodic.tests.md

update kubeadm/kinder tests for 1.16
fixes https://github.com/kubernetes/kubeadm/issues/1743

update kubeadm/kinder tests for 1.16

---

tests/e2e/manifests/verify_manifest_lists.sh

Given the test folder is outside of GOPATH this can cause
a problem if the module name is missing:
```
go: cannot determine module path for source directory
/workspace/k8s.io/kubeadm/tests/e2e/  manifests (outside GOPATH,
no import comments)
```
fixes https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#periodic-manifest-lists

tests/e2e/manifests: fix missing module name

---

kinder/pkg/extract/extract.go

tries for a max of ~300 seconds == 5 minutes when pulling artifacts due to flakes in the CI build process.

kinder: increase timeout for pulling artifacts

---

kinder/pkg/cluster/manager/actions/kubeadm-init.go
kinder/pkg/data/calicomanifests.go

- introduce pkg/data/calicomanifests.go that has CalicoCNI3_8_2.
- in pkg/cluster/manager/actions/kubeadm-init.go pass this manifest
to kubectl using STDIN.
there are two more commits:
- one that fixes kubectl apply problem from
https://github.com/kubernetes/kubeadm/pull/1838
- fix typo in calico manifest that breaks CI

kinder: use a hardcoded manifest when applying CNI 

---

tests/e2e/manifests/verify_manifest_lists.go

as the hyperkube image is no longer published remove it from the "manifest list" tests for >1.17*
fixes:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#periodic-manifest-lists

tests/e2e/manifests: don't test hyperkube for 1.17 and later

---

kinder/cmd/kinder/build/baseimage/baseimage.go
kinder/cmd/kinder/build/nodevariant/nodevariant.go
kinder/cmd/kinder/create/cluster/createcluster.go
kinder/doc/kind-kinder.md
kinder/pkg/constants/constants.go

Little cleanup trying to make easier future upgrades of the kind release

kinder: remove "sigs.k8s.io/kind/pkg/build/node" dependency

---

operator/api/v1alpha1/operation_types.go
operator/api/v1alpha1/runtimetask_types.go
operator/api/v1alpha1/runtimetaskgroup_types.go
operator/controllers/operation_controller.go
operator/controllers/runtimetask_reconcile.go
operator/controllers/runtimetaskgroup_controller.go
operator/controllers/suite_test.go
operator/controllers/util.go
operator/hack/update-goimports.sh
operator/hack/verify-goimports.sh
operator/main.go
operator/operations/factory.go
operator/operations/util.go

This changeset makes operator imports sorted as described in #1867.
I also added `-local k8s.io/kubeadm/operator` to **goimports** command, so it will enforce making the 3rd group of imports belonging to "kubeadm/operator". I don't know if this flag is appreciated across kubernetes org; if it's not, I can remove that.

operator: organize imports

---

kinder/pkg/cluster/manager/actions/cluster-info.go
kinder/pkg/cluster/status/node.go

Fixes: https://github.com/kubernetes/kubernetes/issues/84690
latest release of etcdctl renamed some flags; this PR makes kinder use the right flags according to the kubernetes version installed in the cluster

fix-master-on-v1.16

---

kinder/ci/workflows/discovery-1.17.yaml
kinder/ci/workflows/external-etcd-1.17.yaml
kinder/ci/workflows/kustomize-1.17.yaml
kinder/ci/workflows/skew-1.17-on-1.16.yaml
kinder/ci/workflows/skew-master-on-1.17.yaml
kinder/ci/workflows/upgrade-1.16-1.17.yaml
kinder/ci/workflows/upgrade-1.17-master.yaml

This PR:
- Creates E2E jobs for kubernetes 1.17
- Changes master jobs to use 1.17 instead of 1.16
As proposed in #1871
test-infra PR: https://github.com/kubernetes/test-infra/pull/15077

Create E2E jobs for 1.17

---

kinder/cmd/kinder/build/build.go
kinder/cmd/kinder/kinder.go
kinder/doc/kind-kinder.md

Little cleanup trying to make easier future upgrades of the kind release
Please note that both` kind build node-image` and `kind load` command does not work with kinder images based on docker
Also, kinder offers a `kinder build node-variants` that replaces the above command in all the kubeadm E2E tests and makes it easier to load locally build artifacts for developers.

kinder: remove unused kind cmd

---

kinder/pkg/cluster/manager/actions/kubeadm-init.go

It referred to `kind`, which might have been a small typo or mistake.
In any case it's one tool less to install and you can just copy and paste what's on the screen.

make kinder refer to "kinder get kubeconfig-path"

---

kinder/ci/kubeadm-periodic.tests.md
kinder/ci/workflows/regular-1.14.yaml
kinder/ci/workflows/regular-1.15.yaml
kinder/ci/workflows/regular-1.16.yaml
kinder/ci/workflows/regular-1.17.yaml
kinder/ci/workflows/regular-master.yaml
kinder/ci/workflows/regular-tasks.yaml

Currently these are done using kind and the kind kubetest deployer.
We are switching these test jobs to kinder for consistency
and better control.
The workflows do the following:
- pull a base image
- add artifacts for the target version
- create a 3CP2W cluster
- run cluster-info, e2e-kubeadm and e2e
- export logs, reset, delete the cluster
xref https://github.com/kubernetes/kubernetes/issues/84676
test-infra PR: https://github.com/kubernetes/test-infra/pull/15130

kinder: add a test job family for running regular tests

---

kinder/hack/verify-spelling.sh
kinder/pkg/cluster/manager/actions/cluster-info.go
kinder/pkg/cluster/manager/actions/cluster-info_test.go
operator/hack/verify-spelling.sh

etcdctl needs different cert arguments for 3.4+ and older.
Execute EtcdImage() on the bootstrap control plane to obtain the
active etcd image version. This should solve issues where after
upgrade or skew tests the version of etcdctl does not match
the /kind/version version.
The alternative is to add means to update /kind/version for
certain workflows and "do" actions.

kinder: use the etcd tag version for defining etcdctl flags

---

kinder/pkg/cluster/manager/manage.go
kinder/pkg/cluster/status/node.go

commits:
```
kinder: fix a bug when coping files from or to a container 
kinder: handle errors from Node#CopyTo() and Node#CopyFrom()
kinder: fix typo in manager/manage.go
```
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-kustomize-master

fix a bug in kinder related to 'docker cp'

---

kinder/pkg/cluster/manager/actions/cluster-info.go
kinder/pkg/cluster/manager/actions/cluster-info_test.go
kinder/pkg/cluster/status/node.go

xref https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-16-1-17
```
kinder: do not cache the kubernetesVersion  …
The call is cheap and caching can present issues when the version
is changed in the container.
kinder: call etcdctl flags based on the etcdctl version  …
- call etcdctl from the etcd container and get its version
- append the version specific etcdctl cert flags based on the version
```

kinder: fix more etcd image related issues

---

kinder/ci/workflows/presubmit-upgrade-master.yaml

It performs an upgrade from ci/latest to ci/latest.
The e2e and e2e-kubeadm tasks are in dry-run mode, because
the goal of this test is to check for kinder errors and not
kubeadm / k8s errors.
test infra PR: https://github.com/kubernetes/test-infra/pull/15217

kinder: add a presubmit CI workflow

---

kinder/ci/workflows/presubmit-upgrade-master.yaml

CI presubmit failed due to errors in the workflow file: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeadm/1901/pull-kubeadm-kinder-upgrade-master/1194318256219885568

kinder: fix wrong variables and add missing upgrade

---

kinder/ci/tools/verify-workflow.go
kinder/cmd/kinder/test/workflow/workflow.go
kinder/hack/verify-workflows.sh
kinder/pkg/test/workflow/taskCmdBuilder.go
kinder/pkg/test/workflow/workflow.go

- make verify-workflow.go use logrus, to be consistent with the
underlying API functions it's calling.
- dry-run a workflow as part of verification
- allow passing a io.Writer to workflow.Run, when calling from
kinder use os.Stdout, when called from the verify-workflow pass
ioutil.Discard
- print better message in verify-workflows.sh
- handle missing template vars via "missingkey=error"
- use logrus.Debug for shadowed variables

kinder: improve workflow verification

---

operator/controllers/operation_controller_test.go

Ref: #1920 
/cc @fabriziopandini

kubeadm operator: add unit tests for operation_controller

---

kinder/cmd/kinder/get/get.go
kinder/cmd/kinder/get/kubeconfigpath/kubeconfigpath.go
kinder/cmd/kinder/get/nodes/nodes.go

This PR removes `kind` dependencies when calling `kinder get nodes` and `kinder get kubeconfig-path`. It addresses issue #1902.

kinder: remove kind cluster dependencies

---

kinder/pkg/cluster/manager/actions/copy-certs.go
kinder/pkg/cluster/manager/actions/kubeadm-config.go
kinder/pkg/cluster/manager/actions/kubeadm-init.go
kinder/pkg/cluster/manager/actions/loadbalancer.go
kinder/pkg/cluster/status/node.go

potential fix for https://github.com/kubernetes/kubeadm/issues/1918
Similar flakes were seen in kind when the command "export logs"
is used. The command also uses "/dev/stdin" for copying between
host and container. As much as being a speculation the "/dev/stdin"
flakes could be a Docker bug.
Create a utility function Node#WriteFile that instead of
using /dev/stdin uses a temporary file on the host and copies
the contents of the file to the node.
Use this function in a number of locations instead of using
"docker cp /dev/stdin ...".

kinder: don't use "docker cp /dev/stdin"

---

kinder/cmd/kinder/create/cluster/createcluster.go
kinder/pkg/cluster/manager/create.go
kinder/pkg/cri/containerd/createhelper.go
kinder/pkg/cri/createhelper.go
kinder/pkg/cri/docker/createhelper.go
kinder/pkg/cri/util/util.go

After removing support for the kind config, kinder lost some features.
Some users showed interest in mount volumes (e.g. for mounting sources folders inside containers) and this PR is an MVP for restoring mount volumes.
/area kinder
/kind cleanup
/milestone next
/hold
until release cut

kinder: add --volume option to configure mount volumes on containers

---

kinder/pkg/cluster/status/node.go

With hope that this will explain the occasional flakes
when copying the cluster settings to a node.
could not reproduce this locally, so maybe it's a RAM issue.
yet we do set 9000Mi and kinder takes around 7GB while creating a 3CP,2W cluster.
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cluster-lifecycle/kubeadm-kinder.yaml#L41
xref https://github.com/kubernetes/kubeadm/issues/1918
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-master
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-master/1206284863246700545/build-log.txt
```
time="18:51:58" level=error msg="failed to write cluster settings to node kinder-regular-control-plane-2: failed to write /kinder/cluster-settings.yaml: exit …
```

kinder: enable "echo mode" for copy commands

---

kinder/ci/workflows/discovery-tasks.yaml
kinder/ci/workflows/external-etcd.yaml
kinder/ci/workflows/presubmit-upgrade-master.yaml
kinder/ci/workflows/regular-tasks.yaml
kinder/ci/workflows/skew-x-on-y-tasks-automatic-copy-certs.yaml
kinder/ci/workflows/skew-x-on-y-tasks.yaml
kinder/ci/workflows/upgrade-tasks.yaml

was adding higher verbosity for the upgrade jobs to debug https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-17-master
but instead added it to all workflows.
will probably self-LGTM due to no folks being around during the holidays.

kinder: add higher kubeadm verbosity to all workflow tasks

---

kinder/ci/workflows/kustomize-tasks.yaml
kinder/ci/workflows/upgrade-tasks-automatic-copy-certs.yaml

The previous commit missed these workflows.
https://github.com/kubernetes/kubeadm/pull/1980
self-applying LGTM again to not bother folks during the h-days.

kinder: enable verbose output for two more workflows

---

kinder/hack/verify-golint.sh
kinder/hack/verify-staticcheck.sh
operator/hack/verify-golint.sh

Currently, when we access github.com with HTTP, it is redirected to HTTPS automatically. So this commit aims to replace http://github.com by https://github.com for security.
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>

Replacing 'HTTP' by 'HTTPS' for securing links

---

docs/testing-pre-releases.md

Signed-off-by: SataQiu <1527062125@qq.com>
Ref: #2051

docs: use 'k8s.gcr.io' instead of 'gcr.io/google-containers'

---

tests/e2e/manifests/verify_manifest_lists.go
tests/e2e/manifests/verify_manifest_lists.sh

commits:
> tests/e2e/manifests: use k8s.gcr.io as the GCR bucket
only switches the URL for the bucket
> tests/e2e/manifests: pin the go version and install it using curl
installing go from `debian:stretch` suddenly started returning a version that does not have `go mod`.
download go and install gcc manually.
/assign @SataQiu 
fixes: https://github.com/kubernetes/kubeadm/issues/2051

update the "manifest lists" test for k8s.gcr.io

---

kinder/doc/kind-kinder.md
kinder/pkg/build/base/base.go

This PR remove dependency from sigs.k8s.io/kind/pkg/util.
Important. after this change, kinder can build images only on top of linux/amd64 os, but this should not be a problem because we never tested/aimed to support other os as a base image.
FYI  currently we are using ubuntu:18.04

[kinder] remove dependency kind util

---

kinder/doc/kind-kinder.md
kinder/go.mod
kinder/pkg/cluster/manager/actions/kubeadm-config.go
kinder/pkg/kubeadm/discovery.go
kinder/pkg/kubeadm/kustomize.go

This PR remove dependency from "sigs.k8s.io/kind/pkg/kustomize" by forking some code from older versions of kind.
Please note that kind moved away from kustomize in favor or lighter solutions. In kinder, we are not taking this step yet because the size of the binary is not a major concern at this stage.
/area kinder

[kinder] remove dependency kind kustomize

---

kinder/cmd/kinder/create/create.go

The only valid subcommand for `kinder create` seems to be `kinder create cluster`.

Update help text for 'kinder create'

---

kinder/cmd/kinder/create/cluster/createcluster.go

Fixes #2116
`constants.DefaultNodeImage` is still set to `"kindest/node:latest"` and it is used when building the node image.

Make --image required for kinder create cluster

---

kinder/ci/kubeadm-periodic.tests.md
kinder/ci/workflows/upgrade-master-no-addon-config-maps.yaml

Add a workflow that:
- creates 1CP1W cluster
- inits the CP node
- deletes the kube-proxy and coredns config maps
- joins the worker
- upgrades the CP node (to the same version as init)
This ensures that kubeadm tolerates missing addon config maps.
"upgrade apply" still requires skipping the CoreDNS preflight checks,
but this is controllable by the user.
Skipping the "addon" phase from "init" completely results in a cluster
that does not work, as a proxy / CNI solution has to be deployed for the
"upgrade-prepull*" DS to complete. Potentially replacement addons
can provide a better e2e test for this (in the future).

kinder: add e2e workflow for testing join and upgrade without addon ConfigMap

---

kinder/ci/kubeadm-periodic.tests.md

"Tests without addon ConfigMaps" was recently updated
incorrectly to include a latest-1.18 -> master upgrade.
The upgrade is actually master->master for this test.
https://github.com/kubernetes/kubeadm/blob/master/kinder/ci/workflows/upgrade-master-no-addon-config-maps.yaml

kinder: fix issue in kubeadm-periodic.tests.md

---

kinder/pkg/cluster/manager/actions/smoke-test.go
kinder/pkg/cluster/manager/actions/waiter.go

- Replace `kubectl run` with `kubectl create deployment`
- Wait for service to be reachable before trying to access it
fixes #2117

fix kinder smoke test

---

kinder/ci/workflows/discovery-tasks.yaml
kinder/ci/workflows/external-etcd.yaml
kinder/ci/workflows/kustomize-tasks.yaml
kinder/ci/workflows/presubmit-upgrade-master.yaml
kinder/ci/workflows/regular-tasks.yaml
kinder/ci/workflows/skew-x-on-y-tasks.yaml
kinder/ci/workflows/upgrade-tasks.yaml

xref https://github.com/kubernetes/kubernetes/issues/90761
5 minutes has become more and more flaky for some tasks.
This could be caused by a couple of factors:
1) A scheduling / node regression in core of sort. I think I started
seeing this in my local kubeadm clusters (without kind/kinder)
around 1.16-1.17.
2) Slower infra: GCE VMs / Prow Pods / CR could be involved. Maybe
our jobs have less resources compared to before or maybe it only
happens sometimes.
Increase the timeout for the following tasks to 10m:
- "kubeadm-join": The nodes just don't get ready in time for 3CP2W workflows.
- "e2e-kubeadm": It seems building the suite times-out a lot now.
Maybe the suite just got a little bigger and we were borderline
flaky without catching it before.
- "kubeadm-upgrade": it just timeouts …

kinder: adjust timeouts to attempt to fix flakes

---

kinder/pkg/cluster/manager/actions/images.go

`kubeadm config images list --kubernetes-version=%s` emits a warning -
> WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
The `expected` list of images contains this warning and that results in -
>Some of the required images are not pre-loaded into the container runtime
This PR aims to fix that by redirecting the stderr of kubeadm to `/dev/null`

fix checking of pre-loaded images

---

kinder/pkg/build/alter/alter.go
kinder/pkg/cri/alterhelper.go
kinder/pkg/cri/containerd/alterhelper.go
kinder/pkg/cri/docker/alterhelper.go
kinder/pkg/cri/docker/createhelper.go
kinder/pkg/test/workflow/taskCmdRunner.go

xref https://github.com/kubernetes/kubernetes/issues/90761
first commit is just a typo fix.
second commit:
```
The idea of this change is to reduce the amount of network traffic
kinder e2e test workflows have to do with the attempt to fix flakes.
For 3CP setup etcd has to be pulled 3x~200MB (6x~200MB for upgrade).
After this change it has to be pulled 1x~200MB (2x~200MB for upgrade).
- pre-pull non-kube images for docker and containerd based on the output
of the kubeadm binary for init/join and binary for upgrade.
- pre-load these images for docker during cluster create and upgrade
- for containerd the images are not pre-loaded due to issues related
to the containerd "snapshoter" functionality. add TODOs to resolve
that in the future. one potential fix is to import them on runtime
the …
```

kinder prepull images during build

---

kinder/pkg/build/alter/alter.go
kinder/pkg/cri/alterhelper.go
kinder/pkg/cri/containerd/actionhelper.go
kinder/pkg/cri/containerd/alterhelper.go
kinder/pkg/cri/containerd/createhelper.go
kinder/pkg/cri/docker/alterhelper.go

fixes https://github.com/kubernetes/kubeadm/issues/2142
tested with two separate images:
```
kinder build node-image-variant --base-image kindest/base:v20190403-1ebf15f --with-init-artifacts=./alter/bits/init --with-upgrade-artifacts=./alter/bits/upgrade --loglevel=debug
kinder build node-image-variant --base-image kindest/base:v20191105-ee880e9b --with-init-artifacts=./alter/bits/init --with-upgrade-artifacts=./alter/bits/upgrade --loglevel=debug
```
then for each image:
```
kinder create cluster ...
kinder do kubeadm-init ...
kinder do kubeadm-upgrade ...
```
commits:
```
kinder: don't delete upgrade image tars for containerd
Keep the images in the container for Init and Upgrade for both CRs.
-------
kinder: load init images from tars on cluster creation for containerd
- When pulling …
```

kinder fix issues around containerd base images

---

kinder/pkg/cri/docker/createhelper.go

Attempt to fix flakes related to slow start of docker in the kinder nodes:
"time="07:37:01" level=error msg="timed out waiting for docker to be ready on node kinder-upgrade-worker-1"
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-18-master/1262284866163052547/artifacts/task-02-create-cluster-log.txt
xref https://github.com/kubernetes/kubernetes/issues/90761

kinder: increase waitForDocker timeout to 1m

---

kinder/README.md
kinder/cmd/kinder/build/build.go
kinder/doc/prepare-for-tests.md
kinder/doc/reference.md

The command `kinder build node-image` has been removed by #1875, users should use `kind` directly.
And the `apt` build type has been removed by kind with kubernetes-sigs/kind#585.

kinder: remove the docs about 'kinder build node-image'

---

kinder/ci/workflows/discovery-tasks.yaml
kinder/ci/workflows/external-etcd.yaml
kinder/ci/workflows/kustomize-tasks.yaml
kinder/ci/workflows/regular-tasks.yaml
kinder/ci/workflows/skew-x-on-y-tasks.yaml
kinder/ci/workflows/upgrade-tasks.yaml

Attempt to resolve potential flakes where building the node image
takes more than 10 minutes.
Also increase the timeout for the upgrade task in upgrade-tasks.yaml.
xref https://github.com/kubernetes/kubernetes/issues/90761#issuecomment-647673633

kinder: increase timeout for building node images to 15m

---

kinder/ci/workflows/patches-1.19.yaml
kinder/ci/workflows/patches-master.yaml
kinder/ci/workflows/patches-tasks.yaml
kinder/cmd/kinder/do/do.go
kinder/pkg/cluster/manager/actions/actions.go
kinder/pkg/cluster/manager/actions/kubeadm-init.go
kinder/pkg/cluster/manager/actions/kubeadm-join.go
kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go
kinder/pkg/constants/constants.go

- Add test workflows
- Add the flag "--patches" for "kinder do"
- Bind the flag to init, join, upgrade.
- Support only Nodes that are >= 1.19.
- Use the same directory constant for kustomize / patches "PatchesDir".
xref https://github.com/kubernetes/kubeadm/issues/2046
/kind feature
/area kinder test
/priority important-soon

kinder: support and test the --experimental-patches flag for kubeadm

---

kinder/ci/workflows/patches-tasks.yaml

The +json patch file should include a patch that follows RFC6902.
otherwise kubeadm complains that it cannot parse the given patch file for the explicitly specified format.
(expected)

kinder: fix wrong patch format in patches-tasks.yaml

---

kinder/pkg/cluster/manager/actions/kubeadm-init.go

(this time actually tested the "patches-master" workflow locally)

kinder: add missing --experimental-patches for the "init" action

---

kinder/pkg/build/alter/alter.go
kinder/pkg/cri/alterhelper.go
kinder/pkg/cri/containerd/alterhelper.go
kinder/pkg/cri/docker/alterhelper.go

Pulling the etcd image in the containerd version of the build-container
can error out for unknown reason with "failed to convert whiteout file".
Instead of pulling images using the container runtime in the
build-container, use the container runtime on the host and copy / import
the images as tarballs.
fixes https://github.com/kubernetes/kubeadm/issues/2223
xref https://github.com/kubernetes/kubernetes/issues/93223

kinder: prepull the additional images (pause, etcd..) on the host

---

tests/e2e/manifests/README.md
tests/e2e/packages/verify_packages_install_deb.sh
tests/e2e/packages/verify_packages_published.sh

1. change harcode to hardcode
2. unify indentation with tab
3. gcc is also needed when ./verify_manifest_lists.sh

fix typos comment and indentation in tests/e2e

---

tests/e2e/manifests/verify_manifest_lists.go

verFromURL we get at first is v1.18.6\n, however version.MustParseGeneric can only parse
something like 1.18.6. so we should remove the first and last character
$ curl -s https://storage.googleapis.com/kubernetes-release/release/stable-1.txt
v1.18.6

verify_manifest_lists.go: fix "panic: could not parse "v1.18.6\n" as version [recovered]" issue

---

tests/e2e/manifests/verify_manifest_lists_test.go

Now we haven't test minEstimated.Minor() = 1 situation in func
filterVersions

verify_manifest_lists_test.go: add unit test for minEstimated.Minor = 1

---

kinder/pkg/test/workflow/taskCmdRunner.go

When a task has timed out, ideally the whole process tree should be
terminated with a SIGKILL.
The e2e suite has some caveats with AfterSuite() functions and
these can only contribute noise to the logs. A SIGKILL to
the parent process (Golang command) and the child processes such
as Ginkgo, ensure that everything is terminated right away.
Otherwise, Ginkgo can continue running while the cluster is
being destroyed and fill the logs with errors.
Originally this code was disabled for debugging, but executing it
is mandatory. Add more debug messages to help find problems around
obtaining a pgid or killing a process tree in case failures in CI
are seen again.
fixes https://github.com/kubernetes/kubeadm/issues/2252

kinder: avoid orphaning child processes on task timeouts

---

operator/hack/verify-shellcheck.sh

fix the following issue:
operator/hack/verify-shellcheck.sh: line 44: cd: /root/go/src/github.com/kubernetes/kubeadm/operator/operator: No such file or directory

fix wrong dir

---

operator/hack/verify-shellcheck.sh

shellcheck url has been changed and its breaking the build with the following error:
You are downloading ShellCheck from an outdated URL!
Please update to the new URL:
https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz
For more information, see:
https://github.com/koalaman/shellcheck/issues/1871
PS: Sorry for breaking your build :(

update shellcheck url

---

kinder/hack/verify-all.sh
operator/hack/verify-all.sh

use common function cd_root_path to cd to the root path

---

kinder/hack/verify-shellcheck.sh

1. change to use stable version
2. change shellcheck url since old url is unavailable now

fix wrong kinder shellcheck url

---

kinder/hack/verify-whitespace.sh

fix the following issue:
In ./hack/verify-whitespace.sh line 28:
if [[ ! -z "$TRAILING" ]]; then
^-- SC2236: Use -n instead of ! -z.
For more information:
https://www.shellcheck.net/wiki/SC2236 -- Use -n instead of ! -z.

fix small shellcheck issue

---

kinder/pkg/test/workflow/taskCmdRunner.go

If the process PID no longer exists we can omit killing the process
tree in cleanup(). Passing 0 as the signal to syscall.Kill() is used
to determine if the process is still running.
https://man7.org/linux/man-pages/man2/kill.2.html
"If sig is 0, then no signal is sent, but existence and permission
checks are still performed; this can be used to check for the
existence of a process ID or process group ID that the caller is
permitted to signal."
This avoids errors if the command process already terminated, - e.g:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-17-1-18/1306307188003704834
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-17-1-18/1306307188003704834/build-log.txt
> error: failed …

kinder: make the task runner perform cleanup only on existing processes

---

kinder/ci/workflows/external-etcd.yaml
kinder/ci/workflows/presubmit-upgrade-master.yaml
kinder/ci/workflows/regular-tasks.yaml
kinder/ci/workflows/skew-x-on-y-tasks.yaml
kinder/ci/workflows/upgrade-tasks.yaml

It seems 25 minutes is often times not enough for the suite
(parallel runs), either due to more tests being added
or slower infrastructure.
Increase the suite timeout to 35 minutes to try to solve these
problems in the kubeadm/kinder e2e test jobs.
most of the recent flakes in this Summary:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm
area caused by the 25 minute timeout:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-19-master
but there are also failures around slow infra that cannot build the kubeadm e2e suite in less than 10 minutes:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-1-19/1308645363783045120
(10 should be enough, but this will be investigated separatelly)
fixes: …

kinder: increase e2e test suite timeouts to 35 minutes

---

kinder/ci/workflows/external-ca-tasks.yaml
kinder/pkg/cluster/manager/actions/setup-external-ca.go

the tests are failing as can be seen here:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-external-ca-latest
----
problem 1:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-external-ca-latest/1311057566834364416
join seems flaky and needs more time: 
```
kinder.test.workflow: task-05-join expand_less | 5m0s
-- | --
timeout. The task did not complete in less than 5m0s as expected
```
----
problem 2:
the kubeadm e2e test suite is also failing because the kubeconfig on the host tries to connect the api-server on "localhost" but the serving cert on all CP nodes does not have "localhost" in the SANs:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-external-ca-latest/1311027115340075008

kinder: a couple of fixes for external-ca

---

kinder/ci/workflows/presubmit-upgrade-latest.yaml

The default timeout of 5m causes frequent timeouts.
for example:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubeadm/2313/pull-kubeadm-kinder-upgrade-latest/1311100923589693440

kinder: increase the timeout for kubeadm e2e suite on presubmit

---

kinder/ci/workflows/discovery-1.20.yaml
kinder/ci/workflows/external-etcd-1.20.yaml
kinder/ci/workflows/regular-1.20.yaml
kinder/ci/workflows/skew-1.20-on-1.19.yaml
kinder/ci/workflows/skew-latest-on-1.20.yaml
kinder/ci/workflows/upgrade-1.19-1.20.yaml
kinder/ci/workflows/upgrade-1.20-latest.yaml

reverting the revert:
Reverts kubernetes/kubeadm#2340
bringing back the change from @RA489 that introduced the 1.20 jobs.
the release-1.20 branch of k/k now exists:
https://kubernetes.slack.com/archives/CJH2GBF7Y/p1606827974311000?thread_ts=1606811420.282800&cid=CJH2GBF7Y
https://github.com/kubernetes/kubernetes/tree/release-1.20

Revert "Revert "kinder: add test workflows for 1.20""

---

kinder/pkg/extract/extract.go

The CI artifact location is moving to community maintained.
As part of that the location is changing from:
- gs://kubernetes-release-dev
to:
- gs://k8s-release-dev
Apply this change to kinder.
fixes https://github.com/kubernetes/kubeadm/issues/2355
xref https://github.com/kubernetes/k8s.io/issues/1460

kinder: use "k8s-release-dev" for CI artifacts

---

kinder/pkg/cluster/status/cluster.go
kinder/pkg/cluster/status/node.go
kinder/pkg/constants/constants.go
kinder/pkg/cri/nodes/common/util.go

Kind has migrated to use the new label `io.x-k8s.kind.cluster` and `io.x-k8s.kind.role`.
But Kinder is still using the old labels, this is why the cluster deletion failed.
This PR marks the old labels as DEPRECATED and starts to use the new labels.
Fixes: #2381
Ref: https://github.com/kubernetes-sigs/kind/pull/1074
https://github.com/kubernetes-sigs/kind/commit/a39a4efc8475817f1117026a3259d89524eafc28#diff-980007e783aef4dcb904e3684c6cff1b43a651cbd0134db24f4a45f331adc5fc

kinder: sync ClusterLabelKey and NodeRoleLabelKey with kind

---

tests/e2e/manifests/verify_manifest_lists.go
tests/e2e/manifests/verify_manifest_lists.sh

test/e2e/manifests: use go 1.16
upstream k8s is using 1.16 now.
test/e2e/manifests: remove testing for kube-dns
xref https://github.com/kubernetes/kubeadm/issues/1943
test/e2e/manifests: verify the architecture in image config blobs
xref https://github.com/kubernetes/kubernetes/issues/99656

test/e2e/manifests: update for 1.21

---

kinder/ci/kubeadm-periodic.tests.md
kinder/ci/workflows/skew-1.18-on-1.17.yaml
kinder/ci/workflows/skew-1.19-on-1.18.yaml
kinder/ci/workflows/skew-1.20-on-1.19.yaml
kinder/ci/workflows/skew-kubelet-1.17-on-1.18.yaml
kinder/ci/workflows/skew-kubelet-1.17-on-1.19.yaml
kinder/ci/workflows/skew-kubelet-1.18-on-1.19.yaml
kinder/ci/workflows/skew-kubelet-1.18-on-1.20.yaml
kinder/ci/workflows/skew-kubelet-1.19-on-1.20.yaml
kinder/ci/workflows/skew-kubelet-1.19-on-latest.yaml
kinder/ci/workflows/skew-kubelet-1.20-on-latest.yaml
kinder/ci/workflows/skew-latest-on-1.20.yaml
kinder/ci/workflows/skew-x-on-y-tasks.yaml

on the SIG Node / Arch mailing list there is a discussion around the fact that the kubelet claims support for N-2 skew against the kube-apiserver but currently there are not tests for that.
https://groups.google.com/d/msgid/kubernetes-sig-architecture/CAH1uJ6U4qftRnmWthjYKtBKAzRFFnX7XWLMkSbyVWHUsX8%3DBBg%40mail.gmail.com?utm_medium=email&utm_source=footer
on the side of kubeadm we always recommend that users match their kubelet version with the control plane version and the kubeadm version, but such skew tests can help SIG Node and feature upgrade testing in core.
these commit add tests for version skew testing with kubeadm / kinder:
```
skew-kubelet-1.17-on-1.18.yaml
skew-kubelet-1.17-on-1.19.yaml
skew-kubelet-1.18-on-1.19.yaml
skew-kubelet-1.18-on-1.20.yaml …
```

kinder: add kubelet skew test jobs

---

kinder/ci/workflows/external-ca-1.17.yaml
kinder/pkg/constants/constants.go

```
kinder: remove 1.17 constant …
This constant is unused and 1.17 is out of support.
kinder: remove ci/workflows/external-ca-1.17.yaml …
This workflow was not properly removed when 1.17 went out of support.
```
xref https://github.com/kubernetes/kubeadm/issues/2362
test infra PR:
https://github.com/kubernetes/test-infra/pull/21267

kinder: remove leftover 1.17 workflow and constant

---

kinder/ci/workflows/skew-kubelet-1.17-on-1.18.yaml
kinder/ci/workflows/skew-kubelet-1.17-on-1.19.yaml
kinder/ci/workflows/skew-kubelet-1.18-on-1.19.yaml
kinder/ci/workflows/skew-kubelet-1.18-on-1.20.yaml
kinder/ci/workflows/skew-kubelet-1.19-on-1.20.yaml
kinder/ci/workflows/skew-kubelet-1.19-on-latest.yaml
kinder/ci/workflows/skew-kubelet-1.20-on-latest.yaml
kinder/ci/workflows/skew-x-on-y-tasks.yaml

If a kubelet skew job is running against a kubelet N, skip tests
tagged with:
[MinimumKubeletVersion:(N+1)]
or
[MinimumKubeletVersion:(N+1|N+2)]
depending of the size of the skew.
xref https://github.com/kubernetes/kubernetes/issues/99909

kinder: skip tests tagged with [MinimumKubeletVersion:VERSION]

---

kinder/ci/workflows/skew-x-on-y-tasks.yaml

Remove the quotes or this would fail parsing with:
Error: flag "\"--skip=\\[MinimumKubeletVersion:(1.21)\\]\""
could not be parsed correctly: the argument should start with '--'
added in:
https://github.com/kubernetes/kubeadm/pull/2403
failing tests:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-kubelet-1-20-on-latest/1369480366976405504/artifacts/task-07-e2e-log.txt
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-kubelet-1-20-on-latest

kinder/ci/workflows: remove quotes around --ginkgo-flags

---

tests/e2e/manifests/verify_manifest_lists.sh

`$ curl https://golang.org/dl/go1.16.linux-amd64.tar.gz`
`<a href="https://dl.google.com/go/go1.16.linux-amd64.tar.gz">Found</a>.`
Signed-off-by: Ma Xinjian <maxj.fnst@fujitsu.com>

go download url has changed

---

tests/e2e/manifests/verify_manifest_lists.go

This image is missing in the pre-release, so we have to skip it.
Instead of skipping images like that ideally the release process
should release again this missing image, but looks like this is
complicated.
discussion:
https://kubernetes.slack.com/archives/C2C40FMNF/p1615817136017300?thread_ts=1615817136.017300&cid=C2C40FMNF
fixes https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#periodic-manifest-lists

verify_manifest_lists: don't test conformance:v1.21.0-beta.1

---

kinder/pkg/build/bits/initBits.go
kinder/pkg/kubeadm/config.go

> Mar 26 02:30:25 kind-control-plane kubelet[244]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/100573/pull-kubernetes-e2e-kind-ipv6/1375269122421559296/artifacts/logs/kind-control-plane/kubelet.log
Fix warning logs in e2e testing envs.

change config.yaml instead of args for fail-swap-on

---

kinder/pkg/cluster/manager/actions/assets/kindnet.go
kinder/pkg/cluster/manager/actions/kubeadm-init.go

In CI we use a versioned kubekins image that does not
have go1.16 when testing k8s versions older than 1.21.
This means we have to preserve backwards compatibility
and cannot use "go:embed" until all kubekins versions
in the k8s skew have at least go1.16.
fixes https://github.com/kubernetes/kubeadm/issues/2441

kinder: import the kindnet manifest as source code

---

kinder/ci/workflows/upgrade-latest-no-addon-config-maps.yaml

The test is failing since a missing kube-proxy config map,
now causes the joining node to never become ready.
Rename the kube-proxy CM to ensure a scenario where
the user has a "custom proxy".
Also during upgrade ignore only the CoreDNS* preflight checks.
more details here:
xref https://github.com/kubernetes/kubeadm/issues/2444

kinder: fix a problem in the upgrade test without addons

---

kinder/pkg/constants/constants.go

This constant is unused and 1.18 is out of support.

kinder: remove 1.18 constant

---

docs/managing-e2e-tests.md
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-addons.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-discovery.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-external-ca.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-external-etcd.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-kubelet-x-on-y.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-patches.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-upgrade.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-x-on-y.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder.yaml

Migrate the mailing list for kubeadm/kinder e2e job failure
alerts to "sig-cluster-lifecycle-kubeadm-alerts@kubernetes.io"
in testinfra templates.
Update docs/managing-e2e-tests.md.
fixes https://github.com/kubernetes/kubeadm/issues/2451
test-infra PR: https://github.com/kubernetes/test-infra/pull/22206

kinder: migrate to sig-cluster-lifecycle-kubeadm-alerts@kubernetes.io

---

docs/ha-considerations.md
docs/managing-e2e-tests.md
docs/test-failures.md
docs/updating-command-reference.md
kinder/cmd/kinder/cp/cp.go
kinder/cmd/kinder/exec/exec.go
kinder/doc/reference.md
kinder/pkg/cluster/status/cluster.go
kinder/pkg/cri/host/doc.go
kinder/pkg/kubeadm/patch.go

- remove some more instances of the word "master" and use "control plane"
- migrate links with "master" branch to git.k8s.io/ and sigs.k8s.io.

further cleanup of "master" -> "control plane"

---

kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-kubelet-x-on-y.yaml

Switch the kubelet skew jobs to report to:
sig-node-test-failures+testgrid@googlegroups.com
/cc @ehashman

kinder: update template to use a different SIG node alerts ML

---

docs/ha-considerations.md

The website "https://plndr.io/kube-vip/" is 404 now, and changed to the new domain "https://kube-vip.io/".

docs: fix the bug that kube-vip change the domain name.

---

kinder/pkg/build/alter/alter.go
kinder/pkg/cri/nodes/alterhelper.go
kinder/pkg/cri/nodes/containerd/alterhelper.go
kinder/pkg/cri/nodes/docker/alterhelper.go
kinder/pkg/kubeadm/config.go

Pin the driver to "systemd" in:
- the Docker / containerd config files during image alter
- KubeletConfiguration that kubeadm deploys
xref https://github.com/kubernetes/kubeadm/issues/874

kinder: pin the CR cgroup driver to "systemd"

---

kinder/hack/update-workflows.sh

Fix a small problem I found when working on #2497

kinder: using the well-known GOPATH environment variable in update-workflows.sh instead of HOME

---

kinder/ci/tools/update-workflows/templates/workflows/rootless-tasks.yaml
kinder/ci/workflows/rootless-tasks.yaml

tertgrid fails with the following error:
```
/bin/sh: 1: Bad substitution
chmod: cannot access '/tmp/verify-rootless.sh': No such file or directory
exit status 1
```
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-rootless-latest

Use /bin/bash instead of /bin/sh for verify-rootless task.

---

kinder/ci/tools/update-workflows/templates/workflows/rootless-tasks.yaml
kinder/ci/workflows/rootless-tasks.yaml

The "rootless" e2e test requires strict permissions
for some files like ca.crt. Apparently our existing
"manual" copy-certs method stomps permissions and
ownership ("docker cp" artifact?)
Use the "auto" mode which uses the native logic in kubeadm
that uses a Secret as the transport medium of certs/keys
between control plane nodes. It also stomps permissions, but
has some logic to write private keys with 600 and public
keys/certs with 644, which is sufficient for the "rootless" use case.

kinder: use the "auto" mode for the "rootless" workflow

---

kinder/ci/tools/update-workflows/templates/workflows/rootless-tasks.yaml
kinder/ci/tools/update-workflows/templates/workflows/rootless.yaml
kinder/ci/workflows/rootless-latest.yaml
kinder/ci/workflows/rootless-tasks.yaml

Despite this workflow upgrades from version Foo to version Foo,
kinder uses a mechanism where it searches for artifacts under
"/kinder/upgrade/" on the node image.
This can be improved in the future, but for the time being simply
pass --with-upgrade-artifacts to populate the said folder.

kinder: include upgrade artifacts in rootless workflow

---

docs/testing-pre-releases.md
tests/e2e/packages/verify_packages_install_deb.sh

this was a straight search-replace rather than attempting to converge
toward dl.k8s.io because way too much of this is stale. I tried editing
to update stale info at first, but someone who knows the state of things
needs to do this.
e.g. many of the uris in here are already dead, let alone things like
/bazel and /ci-cross not existing in gs://k8s-release-dev
This is part of https://github.com/kubernetes/k8s.io/issues/2318

use k8s-release-dev instead of kubernetes-release-dev

---

docs/testing-pre-releases.md
kinder/README.md
kinder/doc/reference.md
kinder/pkg/build/bits/initBits.go
kinder/pkg/test/e2e/binary.go

Update references to legacy artifacts locations (`/bazel`, `/ci-cross`, etc).
Fixes: #2529
/hold
I cannot find the `.deb` packages in the `gs://k8s-release-dev/ci/<version>bin/linux/amd64` bucket.
So I worry about `/tests/e2e/packages/verify_packages_install_deb.sh` still doesn't work. 
Did I miss something? @neolit123

update references to legacy artifacts locations

---

docs/testing-pre-releases.md

Related:
- This is part of: https://github.com/kubernetes/k8s.io/issues/2318
- Similar PR: https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/pull/300
- The change this is documenting, which landed 2021-01-14: https://github.com/kubernetes/kubernetes/pull/97087
Document that CI images are pulled from gcr.io/k8s-staging-ci-images, not gcr.io/kubernetes-ci-images

docs: use k8s-staging-ci-images

---

kinder/pkg/cluster/manager/actions/kubeadm-config.go
kinder/pkg/cluster/manager/actions/kubeadm-init.go
kinder/pkg/cluster/manager/actions/kubeadm-join.go
kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go
kinder/pkg/constants/constants.go
kinder/pkg/kubeadm/discovery.go

https://github.com/kubernetes/kubeadm/tree/master/kinder/pkg/cluster/manager/actions
use --config for "init|join" and --patches for "upgrade"
for https://github.com/kubernetes/kubeadm/issues/2046 and https://github.com/kubernetes/kubernetes/pull/104065

Kubeadm patches: use config for newer versions; --experimental-patches for older

---

kinder/pkg/cluster/manager/actions/kubeadm-config.go
kinder/pkg/constants/constants.go
kinder/pkg/kubeadm/componentpatches.go
kinder/pkg/kubeadm/discovery.go

The patches adding is inside if-else. 
```
if options.discoveryMode != TokenDiscovery && !(n == c.BootstrapControlPlane()) {
```
Move it out to fix the ci-kubernetes-e2e-kubeadm-kinder-patches-latest failure
Failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-patches-latest/1425293204315443200
See https://github.com/kubernetes/kubeadm/issues/2046#issuecomment-897035731

add patches for join/init/upgrade to the right place

---

kinder/pkg/cluster/manager/actions/kubeadm-init.go
kinder/pkg/cluster/manager/actions/kubeadm-join.go
kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go
kinder/pkg/constants/constants.go
kinder/pkg/kubeadm/componentpatches.go

- Looks like /tmp is not a good location to copy files to.
Either they silently fail to copy to /tmp or they throw an
error that a /tmp/sub-dir like "kinder-patches" is not a directory
(but it is). Searching for the related errors online:
- Error response from daemon: extraction point is not a directory
- Error: No such container:path: kinder-patches-control-plane-1:/tmp/kubeadm-patches
does not provide much context on why this is happening.
Use "/kinder/patches" instead of "/tmp...".
- Include missing error return in copyPatchesToNode()
- Remove host OS check about the patch directory. We don't need this check
because an earlier step should copy the patches from host to container.
If the patch directory in the container is different from the patch
directory on the host it would fail.
- …

kinder: fix failing patches e2e tests

---

.github/ISSUE_TEMPLATE.md
README.md

fixing a broken link from https://github.com/kubernetes/kubeadm/pull/2544
The correct link for k8s support is:
https://git.k8s.io/kubernetes/SUPPORT.md

README/ISSUE_TEMPLATE: fix wrong link to k8s support

---

.github/workflows/support-command.yaml

Users tend to skip our notes about not using the issue tracker
for support questions.
This change adds a GitHub action handler for a `/support`
command.
Commenting with the command on an issue will:
- Provide a friendly message where to find support links.
- Label the issue with `kind/support`.
- Close the issue.

github/workflows: add action for a "/support" command

---

.github/workflows/support-command.yaml

If the commenting GitHub users pass a comment without the "/support"
command the GitHub action will throw an error:
"Error: Comment didn't contain a valid slash command"
This seems like a missing feature in the xt0rted/slash-command-action
extension. Include a workaround that skips the comment/close/label
steps if the command is not present.
Also pin to ubuntu-20.04 instead of latest.
if github actions support regexp conditions, the xt0rted/slash-command-action extension would not have been needed
and one could use something like `if: regexpmatch(somestr, exp`).
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

github/workflows/support-command: don't error on comments with no command

---

kinder/ci/tools/update-workflows/templates/workflows/skew-x-on-y.yaml
kinder/ci/workflows/skew-1.21-on-1.20.yaml
kinder/ci/workflows/skew-1.22-on-1.21.yaml
kinder/ci/workflows/skew-1.23-on-1.22.yaml
kinder/ci/workflows/skew-latest-on-1.23.yaml

Once the k/k branch for a new release X is cut, the k/k master branch
starts pointing out at k8s version X+1.
Until we update our workflows (normally we try to
do it on the same date as the new branch cut) we will have failing
"latest" e2e tests because they will try to use kubeadm from master (X+1)
but the tracked version in the workflow will be still at X-1 (because
we don't know about the latest X release branch yet). Example - kubeadm
is at 1.24.0-pre but control plane and kubelet are at 1.22 still.
This n-2 is not a supported skew and kubeadm init/join will fial.
We have a workaround for control plane versions built in kubeadm
when 1.24.0 is a prerelease, but we don't have a solution for the
kubelet version preflight check error that will happen.
To avoid this temporary problem we …

kinder: ignore KubeletVersion preflight error for x-on-y workflows

---

kinder/ci/tools/update-workflows/templates/workflows/discovery-tasks.yaml
kinder/ci/tools/update-workflows/templates/workflows/external-ca-tasks.yaml
kinder/ci/tools/update-workflows/templates/workflows/external-etcd-tasks.yaml
kinder/ci/tools/update-workflows/templates/workflows/patches-tasks.yaml
kinder/ci/tools/update-workflows/templates/workflows/presubmit-upgrade-latest.yaml
kinder/ci/tools/update-workflows/templates/workflows/skew-x-on-y-tasks.yaml
kinder/ci/tools/update-workflows/templates/workflows/upgrade-latest-no-addon-config-maps.yaml
kinder/ci/tools/update-workflows/templates/workflows/upgrade-tasks.yaml
kinder/ci/workflows/discovery-tasks.yaml
kinder/ci/workflows/external-ca-tasks.yaml
kinder/ci/workflows/external-etcd-tasks.yaml
kinder/ci/workflows/patches-tasks.yaml
kinder/ci/workflows/presubmit-upgrade-latest.yaml
kinder/ci/workflows/skew-x-on-y-tasks.yaml
kinder/ci/workflows/upgrade-latest-no-addon-config-maps.yaml
kinder/ci/workflows/upgrade-tasks.yaml
kinder/pkg/cluster/manager/actions/cluster-info.go

Switch all e2e test workflows to use containerd as the CR for the time
being. Dockershim is being removed from k/k and until cri-dockerd
gains maintainer traction we should avoid setting it up our selfs
for the sake of testing Docker as the CR.
Technically the dockershim removal only affects "latest" workflows
but this change will apply it to all k/k branches. Once and if
cri-dockerd is testable we can add a single workflow for Docker
as the CR.
xref https://github.com/kubernetes/kubeadm/issues/1412#issuecomment-989127286

kinder: switch all workflows to containerd

---

.github/ISSUE_TEMPLATE.md

Often tickets are lacking information about the
used container runtime and CNI plugin.
With the built-in Docker support being dropped in 1.24,
kubelet failures would mean the user has not read the release notes
or has not migrated to a different CR yet.

.github/ISSUE_TEMPLATE: update to include CNI/CRI

---

kinder/pkg/cluster/manager/actions/waiter.go

With UnversionedKubeletConfigMap going Beta in 1.24
and enabled by default, we want to match what kubeadm is doing:
- look of the new name of CM
- if that fails fallback to the old CM name
leave a TODO to remove this extra handling once 1.24
goes out of support. This would mean that all tested
versions of kubeadm only have UnversionedKubeletConfigMap=true
and the new CM name.
xref https://github.com/kubernetes/kubeadm/issues/1582
xref https://github.com/kubernetes/kubernetes/pull/108027
(does not depend strictly on the this PR)
NOTE: i'm not touching the only e2e test workflow for this because it already excercises the case for upgrading from a state with old names -> new names.
https://github.com/kubernetes/kubeadm/blob/main/kinder/ci/workflows/unversioned-kubelet-cm-tasks.yaml#L113-L125 …

kinder: add handling of the new/old kubelet-config map

---

tests/e2e/manifests/verify_manifest_lists.go

Related:
- https://github.com/kubernetes/k8s.io/issues/3411
Verify the manifests lists registry.k8s.io in replacement of k8s.gcr.io
See: https://groups.google.com/d/msgid/kubernetes-sig-testing/CANw6fcFgKaCLLiuY_8TBp%3DKWROHZbuj1FYWAfyGW6XOQ%3D_nLUA%40mail.gmail.com?utm_medium=email&utm_source=footer
Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

k8s-infra: verify manifests for registry.k8s.io

---

kinder/pkg/kubeadm/config.go

It seems the kernel doesn't allow to set some conntrack fields
from non-init netns because they are global, so setting it in a
namespaces leaks it to other namespace:
netfilter: conntrack: Make global sysctls readonly in non-init netns
torvalds/linux@671c54e
By default kube-proxy tries to set nf_conntrack_max, that is readonly,
hence failing and the kproxy pods fail to start crashlooping.
Ref: kubernetes-sigs/kind#2241 kubernetes-sigs/kind#2240

don't set conntrack parameters in kube-proxy

---

tests/e2e/manifests/verify_manifest_lists.go

- Fix a couple of errors that happen after the
go 1.18 version bump in kubekins (the image used
in CI/test-infra testing). The errors are fmt.Println / newline related.
- Also fix some typos.
failing tests:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#periodic-manifest-lists

test/e2e/manifests: fix some errors for go 1.18

---

OWNERS
kinder/OWNERS

subproject or SIG labels are not needed on subproject PRs/issues as they are implied.
helps for better org wide triage on SIG CL tickets, coming from third parties.
add kinder label to kinder OWNERs file.

remove SIG / kubeadm label from OWNERS files

---

kinder/ci/tools/update-workflows/templates/workflows/dryrun-tasks.yaml
kinder/ci/workflows/dryrun-tasks.yaml

xref: https://github.com/kubernetes/kubeadm/issues/2653#issuecomment-1104535529

kinder: ensure the container runtime is started before executing dryrun e2e test

---

.github/ISSUE_TEMPLATE.md
README.md

the kubernetes document url 'https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/' is changed to 'https://kubernetes.io/docs/tasks/debug/debug-cluster/'

update kubernetes url

---

kinder/go.mod
kinder/go.sum

When I try to run `../kubeadm/kinder/ci/kinder-run.sh skew-latest-on-1.24`, I met some errors for old x/sys
```
/Users/pacoxu/go/pkg/mod/golang.org/x/sys@v0.0.0-20201107080550-4d91cf3a1aaf/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
/Users/pacoxu/go/pkg/mod/golang.org/x/sys@v0.0.0-20201107080550-4d91cf3a1aaf/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
/Users/pacoxu/go/pkg/mod/golang.org/x/sys@v0.0.0-20201107080550-4d91cf3a1aaf/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable
/Users/pacoxu/go/pkg/mod/golang.org/x/sys@v0.0.0-20201107080550-4d91cf3a1aaf/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or …
```

upgrade golang.org/x/sys-upgrade to 20220520151302

---

kinder/pkg/build/alter/alter.go
kinder/pkg/cri/host/archive.go

During the fixup of image tarbals if the kubeadm binary is
at least 1.25.0-0, modify k8s.gcr.io to registry.k8s.io.
Leave to TODOs to clean the hack once 1.25 kubeadm / 1.24 k8s
is no longer tested.
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest-on-1-24
xref https://github.com/kubernetes/kubeadm/issues/2671

kinder: apply a hack to handle the registry.k8s.io transition bugs

---

kinder/pkg/cluster/manager/actions/kubeadm-join.go

During join of worker nodes kinder always passes to kubeadm
JoinConfiguration that has a Patches.Directory.
If the directory does not exist kubeadm will error out.
Always create the directory for worker nodes.
This was already done for the "init" node and for "join" control
plane nodes.
fixes failing tests such as:
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest
xref https://github.com/kubernetes/kubeadm/issues/1682

kinder: make sure worker nodes also get a patches dir created

---

kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-addons.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-discovery.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-dryrun.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-external-ca.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-external-etcd.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-kubelet-x-on-y.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-patches.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-rootless.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-upgrade.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-x-on-y.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder.yaml

Ensure prowjobs will run in the community infrastructure
Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

sig-k8s-infra: Default prowjobs to k8s-infra

---

kinder/ci/tools/update-workflows/templates/workflows/discovery-tasks.yaml
kinder/ci/tools/update-workflows/templates/workflows/external-ca-tasks.yaml
kinder/ci/tools/update-workflows/templates/workflows/external-etcd-tasks.yaml
kinder/ci/tools/update-workflows/templates/workflows/patches-tasks.yaml
kinder/ci/tools/update-workflows/templates/workflows/presubmit-upgrade-latest.yaml
kinder/ci/tools/update-workflows/templates/workflows/regular-tasks.yaml
kinder/ci/tools/update-workflows/templates/workflows/rootless-tasks.yaml
kinder/ci/tools/update-workflows/templates/workflows/skew-x-on-y-tasks.yaml
kinder/ci/tools/update-workflows/templates/workflows/upgrade-latest-no-addon-config-maps.yaml
kinder/ci/tools/update-workflows/templates/workflows/upgrade-tasks.yaml
kinder/ci/workflows/discovery-tasks.yaml
kinder/ci/workflows/external-ca-tasks.yaml
kinder/ci/workflows/external-etcd-tasks.yaml
kinder/ci/workflows/patches-tasks.yaml
kinder/ci/workflows/presubmit-upgrade-latest.yaml
kinder/ci/workflows/regular-tasks.yaml
kinder/ci/workflows/rootless-tasks.yaml
kinder/ci/workflows/skew-x-on-y-tasks.yaml
kinder/ci/workflows/upgrade-latest-no-addon-config-maps.yaml
kinder/ci/workflows/upgrade-tasks.yaml
kinder/pkg/cri/nodes/containerd/alterhelper.go

```
kinder: do not patch in systemd driver in config.toml
Newer kind base images have the option already and patching
it results in duplicate entries and errors.
```
```
kinder: update workflows to use the latest kind base image
The latest kind base image has newer containerd, which
hopefully works with all k8s versions that we are testing.
```
fixes https://github.com/kubernetes/kubernetes/issues/113619

kinder: use new kind base image

---

.github/workflows/support-command.yaml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

kinder/hack/orderimports/orderimports.go
kinder/pkg/cri/host/archive.go

Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
comparing with == will fail on wrapped errors. Use errors.Is to check for a specific error

Use errors.Is to check for a specific error

---

docs/testing-pre-releases.md

This PR updates the registry from `k8s.gcr.io` to `registry.k8s.io`
Issue: https://github.com/kubernetes/k8s.io/issues/4738

Update registry k8s.gcr.io -> registry.k8s.io

---

docs/testing-pre-releases.md
kinder/pkg/extract/extract.go
tests/e2e/manifests/verify_manifest_lists.go

This commit improves the URL handling for resource extraction and version filtering processes. The following changes were made:
In the kinder/pkg/extract/extract.go file:
The releaseBuildURepository constant was updated to use the new "https://dl.k8s.io/release" URL for release builds. In the tests/e2e/manifests/verify_manifest_lists.go file:
The URL used in the filterVersions() function was updated to use the new "https://dl.k8s.io/release" URL for retrieving stable versions.
/kind cleanup
There are still references to https://storage.googleapis.com/kubernetes-release instead of https://dl.k8s.io/
dl.k8s.io is the correct advertised download host and will eventually move to be fastly shielding a fully community-owned bucket
ref: https://github.com/kubernetes/k8s.io/issues/2396

fix: use dl.k8s.io, not kubernetes-release bucket

---

docs/testing-pre-releases.md

/kind cleanup
This PR removes reference to an unneeded script in `testing-pre-releases.md`. The entire section was also minorly updated to read a bit more smoothly. 
ref: https://github.com/kubernetes/kubeadm/issues/2876

docs: cleanup reference to `/cluster/` scripts

---

.github/workflows/support-command.yaml

fixes https://github.com/kubernetes/kubeadm/issues/2892
https://github.com/ben-z/actions-comment-on-issue is not updated for a long time. I will try to fix it there as well in https://github.com/ben-z/actions-comment-on-issue/pull/3. 
The current `pacoxu/actions-comment-on-issue@1.0.3` is verified in https://github.com/pacoxu/kubeadm/issues/1

use pacoxu/actions-comment-on-issue@1.0.3

---

.github/workflows/support-command.yaml

Node.js 12 actions are deprecated. need to update xt0rted/slash-command-action@v1 to use Node.js 16.
For more information see: [GitHub Actions: All Actions will begin running on Node16 instead of Node12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12)
In addition, I added Dependabot to help automatically update the dependencies.

Bump xt0rted/slash-command-action from v1 to v2

---

kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-addons.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-discovery.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-dryrun.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-external-ca.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-external-etcd.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-kubelet-x-on-y.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-learner-mode.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-patches.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-rootless.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-upgrade-addons-before-controlplane.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-upgrade.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-x-on-y.yaml
kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder.yaml

This reverts commit e47366886e79972fa4e825e754219cda8546c08a.
Because of [EKS cluster instability](https://github.com/kubernetes/k8s.io/issues/5473) issues we decided to move kubeadm jobs back to GKE cluster. This has been discussed on yesterday's sig-infra-meeting (unfortunately the video hasn't been uploaded yet). Putting it shortly, we have a suspicion that those jobs are problematic and want to see if moving them back to GKE improves stability of EKS clusters.
/assign @xmudrii 
/cc @dims @ameukam

Revert "kinder: use eks cluster in test-infra jobs"

---

kinder/pkg/cluster/status/cluster.go

Kinder fails during cluster creation, when Docker CLI 24.0.5+ is installed on local machine.
```
DEBU[15:37:35] Reading container list for cluster kind      
DEBU[15:37:35] Running: docker ps -q -a --no-trunc --filter label=io.k8s.sigs.kind.cluster=kind --format {{.Names}} 
DEBU[15:37:35] Adding node WARNING: Ignoring custom format, because both --format and --quiet are set. to the cluster 
DEBU[15:37:35] Running: docker inspect -f {{index .Config.Labels "io.k8s.sigs.kind.role"}} WARNING: Ignoring custom format, because both --format and --quiet are set. 
ERRO[15:37:35] failed to get "io.k8s.sigs.kind.role" label: exit status 1 
```
this is because the most recent `docker ps` command does not allow to specify both --format and --quiet parameters.
(please see similar issue …

kinder: compatible with Docker CLI 24.0.5+

---

docs/managing-e2e-tests.md
docs/release-cycle.md
tests/e2e/README.md
tests/e2e/manifests/README.md

**What this PR does / why we need it:**
Fixes a bunch of broken links to testgrid dashboard.
**Which issue(s) this PR fixes:**
This is related to an umbrella issue and fixes a task of the same:
https://github.com/kubernetes/test-infra/issues/30370

fix broken links to testgrid dashboard

---

OWNERS
kinder/OWNERS

kinder/OWNERS: remove the list of approvers / reviewers and only add the labels. The root OWNERS is what should be used.
please see:
https://github.com/kubernetes/kubernetes/pull/120598
https://github.com/kubernetes/kubernetes/pull/120598#issuecomment-1715370149

OWNERS: move fabriziopandini to emeritus, remove RA489

---

kinder/go.mod
kinder/pkg/cri/nodes/containerd/alterhelper.go
kinder/pkg/cri/nodes/containerd/config/config.go
kinder/pkg/cri/nodes/containerd/config/config_test.go

kinder: configure containerd to use the sandbox image recommended by kubeadm when building the node image

kinder: configure containerd to use the sandbox image recommended by kubeadm when building the node image

---

.github/workflows/support-command.yaml

https://github.com/ben-z/actions-comment-on-issue/releases/tag/1.0.3  included the fix: https://github.com/ben-z/actions-comment-on-issue/pull/3.
See https://github.com/kubernetes/kubeadm/pull/2893.

use ben-z/actions-comment-on-issue back

---

kinder/ci/tools/update-workflows/templates/workflows/super-admin-tasks.yaml
kinder/ci/workflows/super-admin-tasks.yaml

Without the quotes these (CMD) commands cannot be expanded properly.
xref https://github.com/kubernetes/kubeadm/pull/2949
xref https://github.com/kubernetes/kubeadm/issues/2414

kinder: fix missing quotes in super-admin-tasks.yaml

---

kinder/ci/kubeadm-periodic.tests.md

- preflight check KubeletVersion behavior change
https://github.com/kubernetes/kubeadm/pull/2950

Update skew change in v1.29 from n-1 to n-3

---

kinder/ci/tools/update-workflows/templates/workflows/super-admin-tasks.yaml
kinder/ci/workflows/super-admin-tasks.yaml

Add tests that ensure that
/etc/kubernetes/pki/apiserver-kubelet-client.crt uses "kubeadm:cluster-admins" instead of "system:masters".

kinder: add tests for /etc/kubernetes/pki/apiserver-kubelet-client.crt

---

kinder/ci/tools/update-workflows/templates/workflows/super-admin-tasks.yaml
kinder/ci/workflows/super-admin-tasks.yaml

Calling "rm -f" should be done with "exit 1".
Let's see if docker flakes and sometimes this does not work.
Do proper cleanup of all files in /etc/kubernetes and /etc/kubernetes/pki.
fixes https://github.com/kubernetes/kubeadm/issues/2961

kinder: do proper cleanup in the super-admin-tasks.yaml workflow

---

kinder/ci/tools/update-workflows/templates/workflows/super-admin-tasks.yaml
kinder/ci/workflows/super-admin-tasks.yaml

During "bash -c" expansion if the following is called:
`  rm -f path/*.*`
bash (for some reason) will single quote the path because of the '*':
`  rm -f 'path/*.*'`
This is actually no longer a valid wildcard, as * inside a '...' is not expanded. To prevent that use double-quotes:
`  rm -f "path/*.*"`
xref https://github.com/kubernetes/kubeadm/pull/2962#discussion_r1392160039

kinder: double-quote 'rm -f' paths to avoid single quotes

---

kinder/pkg/build/alter/alter.go
kinder/pkg/build/bits/initBits.go

During the "altering" of the node image used by kinder, there are two download stages, one to download the init artifacts and one to download upgrade artifacts.
For some e2e workflows we have matching init and upgrade versions. This is done just to test the upgrade command and not perform an actual upgrade. It causes the same artifacts to be downloaded two times, which is slow.
During the preparation of bits installers, check if the init/upgrade versions match. If so, tell the upgrade bits installer to use the init directory as install source. This results in just copying the bits from the host, instead of downloading them again.

kinder: optimize the preparation of upgrade artifacts

---

kinder/pkg/build/alter/alter.go
kinder/pkg/cluster/manager/actions/kubeadm-init.go
kinder/pkg/cluster/manager/actions/kubeadm-join.go
kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go
kinder/pkg/cluster/manager/actions/waiter.go
kinder/pkg/constants/constants.go
kinder/pkg/cri/host/archive.go

- Remove the repository replace from k8s.gcr.io -> registry.k8s.io
- Remove "kubelet-config-x.yy" handling, use "kubelet-config"
- Stop untainting "master" taints, only untaint control-plane taints
- Stop handling --experimental-patches, use --patches
xref https://github.com/kubernetes/kubeadm/issues/2910

kinder: remove the handling of 1.25 and older versions of k8s

---

kinder/ci/tools/update-workflows/templates/workflows/upgrade-latest-no-addon-config-maps.yaml
kinder/ci/workflows/upgrade-latest-no-addon-config-maps.yaml
kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go

During the kinder "kubeadm-upgrade" action, "upgrade apply"
is executed, but "upgrade plan" is not. To ensure better coverage
ensure "upgrade plan" is called as well. We have this command
as part of the kubeadm upgrade docs, so it makes sense to have
it here.
Ensure that "plan" is also called during the
"upgrade-latest-no-addon-config-maps" workflow.
NOTE: untested locally, but the presubmit job here should catch problems. i think this is all that has to be done.
fixes https://github.com/kubernetes/kubeadm/issues/2971

kinder: call "upgrade plan" before "upgrade apply"

---

kinder/ci/tools/update-workflows/templates/workflows/discovery-tasks.yaml
kinder/ci/workflows/discovery-tasks.yaml
kinder/cmd/kinder/do/do.go
kinder/pkg/cluster/manager/manage.go

- If the --only-node flag specifies an unknown node name, kinder should throw an error.
- Update discovery workflows to pass correct node suffixes "-N" instead of "N", and also missing number for the first worker.
this actually meant that our discovery tests were not running properly as worker nodes were never joined using the various discovery modes in the discovery-tasks.yaml.
related to CI failures:
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-discovery-latest
and this PR:
https://github.com/kubernetes/kubernetes/pull/122619

kinder: fix a bug related to --only-node usage

---

kinder/ci/tools/update-workflows/templates/workflows/super-admin-tasks.yaml
kinder/ci/workflows/super-admin-tasks.yaml

xref https://github.com/kubernetes/kubeadm/issues/2414#issuecomment-1929099638
kubeadm 1.29 had code that creates the super-admin.conf file on upgrade. the same code is removed in kubeadm 1.30. Update the super-admin kinder workflow to reflect this change.

kinder: update super-admin workflow for 1.30

---

kinder/ci/tools/update-workflows/templates/workflows/super-admin-tasks.yaml
kinder/ci/workflows/super-admin-tasks.yaml

The super-admin.conf file was no longer expected after upgrade, thus we don't have to read the file and check its subject.
follow up on https://github.com/kubernetes/kubeadm/pull/3012#issuecomment-1931579134

kinder: apply yet another fix for super-admin workflow

---

kinder/pkg/cri/host/pull.go

I was wondering why each time I use `kinder create cluster ...`, connections to `auth.docker.io` and `registry-1.docker.io` would be made. Then I found this typo.
Besides, to keep in accordance with KinD, I think that `imagePullPolicy: "Never"` can be provided **(or becoming configurable)** in `kinder/pkg/kubeadm/config.go` (variable `configTemplateBetaV2` and `configTemplateBetaV3`) to make clustion creation process fully offline-friendly.
If I were wrong, please point out. Thanks!
edit neolit123
fixes https://github.com/kubernetes/kubeadm/issues/3059

Update pull.go: Fix Typo, And a suggestion

---

kinder/pkg/build/alter/alter.go
kinder/pkg/cluster/manager/actions/assets/kindnet.go

The CNI (kindnet) image was the only image that was not prepulled during the creation of a node image. This allows kinder to deploy the cluster without every node having to pull the CNI image.

kinder: prepull the kindnet image when building the node image

---

docs/ha-considerations.md

Update haproxy and keepalived config

---

kinder/ci/tools/update-workflows/templates/workflows/external-ca-tasks.yaml
kinder/ci/workflows/external-ca-tasks.yaml

The workflow already includes upgrade artifacts with the same k8s version. Perform upgrade and do cluster-info and kubeadm-e2e before and after the upgrade.
xref https://github.com/kubernetes/kubeadm/issues/3055
/hold
hold until https://github.com/kubernetes/kubernetes/pull/124682 merges as these changes will fail on 1.29 otherwise.

kinder: include upgrades and cluster-info in external CA workflows

---

kinder/pkg/cluster/manager/actions/actions.go
kinder/pkg/cluster/manager/actions/kubeadm-config.go
kinder/pkg/cluster/manager/actions/kubeadm-reset.go
kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go
kinder/pkg/kubeadm/componentpatches.go
kinder/pkg/kubeadm/config.go

When executing "kubeadm reset" or "kubeadm upgrade", if the kubeadm version is 1.31 (or pre-release) pass the "--config" flag with the v1beta4 kinds. Else,
continue to call the flags for a given command.
Additionally:
- Call "kubeadm upgrade diff" on the primary CP node after calling "upgrade plan".
- Fallback to the /kinder/upgrade/version during upgrade if the provided version is different.
includes some smaller improvements like printing a config that is prepared for a command on multiple lines.
xref https://github.com/kubernetes/kubeadm/issues/2890

kinder: use "--config" for kubeadm "reset" and "upgrade"

---

kinder/pkg/cluster/manager/actions/kubeadm-config.go

fixes failing test job:
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-patches-latest
fixes https://github.com/kubernetes/kubernetes/issues/125957
after this change:
- https://github.com/kubernetes/kubeadm/pull/3086
because of this the UpgradeConfiguration was missing on secondary control plane nodes and patches (as present in the config) were not applied.

kinder: fix typo in kubeadm-config.go

---

kinder/ci/tools/update-workflows/templates/workflows/dryrun-tasks.yaml
kinder/ci/workflows/dryrun-tasks.yaml

kubeadm: enable join dryrun e2e tests without a real control plane
Ref: #2653

kubeadm: enable join dryrun e2e tests

---

kinder/ci/tools/update-workflows/templates/workflows/dryrun-tasks.yaml
kinder/ci/workflows/dryrun-tasks.yaml

kubeadm: increase timeout for dryrun-without-cluster
Hopefully, the execution can be complete in 15 minutes. Not sure what timeout should be set to.
fix: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kubeadm-kinder-dryrun-latest/1856721175695069184

kubeadm: increase timeout for dryrun-without-cluster

---

kinder/ci/tools/update-workflows/templates/workflows/instance-config-tasks.yaml
kinder/ci/workflows/instance-config-tasks.yaml

Add tests for https://github.com/kubernetes/kubernetes/pull/129278 and https://github.com/kubernetes/kubernetes/pull/129279

replenish e2e test for kubelet instance config

---

kinder/pkg/cluster/manager/actions/actions.go
kinder/pkg/cluster/manager/actions/kubeadm-config.go
kinder/pkg/cluster/manager/actions/kubeadm-init.go
kinder/pkg/cluster/manager/actions/kubeadm-join.go
kinder/pkg/cluster/manager/actions/kubeadm-reset.go
kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go
kinder/pkg/constants/constants.go
kinder/pkg/kubeadm/config.go

refer to https://github.com/kubernetes/kubernetes/pull/129401
After we add `SystemVerification` check in upgrade, we need to skip in some kinder testing.
This PR follows the suggestions https://github.com/kubernetes/kubernetes/pull/129401#pullrequestreview-2525461483 to move flags to configurations.
- don't pass the --ignore-preflight errors as flags for commands.
- pass them via config in the big config that has all the config 'kinds'.

move ignore preflight checks from flag to kubeadm configurations

---

kinder/ci/tools/update-workflows/templates/workflows/upgrade-no-addon-config-maps-tasks.yaml
kinder/ci/workflows/upgrade-no-addon-config-maps-tasks.yaml

Add two more tasks in the workflow to account for the addition of 'disabled: true' fields in v1beta4:
- Patch the ClusterConfiguration before upgrade to disable addons.
- Make sure the addon ConfigMaps don't exist after upgrade.
xref
- https://github.com/kubernetes/kubernetes/pull/129418
- https://github.com/kubernetes/kubeadm/issues/3137

kinder: improve the no-addons workflow

---

kinder/ci/tools/update-workflows/templates/workflows/upgrade-no-addon-config-maps-tasks.yaml
kinder/ci/workflows/upgrade-no-addon-config-maps-tasks.yaml

Fixes https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-no-addons-latest
Fixes #3144
```
/bin/sh -c docker exec kinder-upgrade-control-plane-1 kubectl get cm kube-proxy -n kube-system --kubeconfig /etc/kubernetes/admin.conf && exit 1
docker exec kinder-upgrade-control-plane-1 kubectl get cm coredns -n kube-system --kubeconfig /etc/kubernetes/admin.conf && exit 1
Error from server (NotFound): configmaps "kube-proxy" not found
Error from server (NotFound): configmaps "coredns" not found
exit status 1
```
/cc @neolit123

exit 0 after checking addon configmap existences

---

docs/testing-pre-releases.md

https://storage.googleapis.com/k8s-release-dev/ci still exists and is used by kinder on each run to download CI artifacts.
If it gets removed we can update code and the related docs.
Until then don't reference the gs:// URLs for that bucket.
fixes https://github.com/kubernetes/kubeadm/issues/2876
- https://github.com/kubernetes/kubeadm/issues/2876
> https://github.com/kubernetes/k8s.io/issues/2396 (when this is closed we can update k/kubeadm)
- https://github.com/kubernetes/k8s.io/issues/2396
was closed. not clear if https://storage.googleapis.com/k8s-release-dev/ci will be replaced with something else, but we will know right away as it will break all jobs here:
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm

docs: don't reference gs://k8s-release-dev/ci/

---

kinder/ci/tools/update-workflows/templates/workflows/wait-for-all-control-plane-components-tasks.yaml
kinder/ci/tools/update-workflows/templates/workflows/wait-for-all-control-plane-components.yaml
kinder/ci/workflows/wait-for-all-control-plane-components-latest.yaml
kinder/ci/workflows/wait-for-all-control-plane-components-tasks.yaml

xref
- https://github.com/kubernetes/kubeadm/issues/2907
this k/k pr merged, so we'd like to test the fg disabled case:
- https://github.com/kubernetes/kubernetes/pull/129620

kinder: switch WaitForAllControlPlaneComponents workflow to false

---

tests/e2e/manifests/verify_manifest_lists.go

kubeadm: fix periodic-kubernetes-e2e-manifest-lists failing test

---

kinder/ci/kinder-run.sh
tests/e2e/manifests/verify_manifest_lists.sh

- the old go 1.16 is throwing a strange error
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/periodic-kubernetes-e2e-manifest-lists/1896113622615068672
```
./verify_manifest_lists.go:186:14: non-constant format string in call to fmt.Printf
FAIL	command-line-arguments [build failed]
FAIL
```
but the code is
`		fmt.Printf("%s%s", v.String(), sep)`
locally with newer go this error is not reproducible.
- bump to go 1.24 in varify_manifest_lists.sh and pin the api-machinery version to 0.32.
- print the go version in kinder / manifest test scripts.

print go version and update to go 1.24 of verify-manfiest-lists.sh

---

.github/workflows/support-command.yaml

our `/support` command stopped working with this error: https://github.com/kubernetes/kubeadm/actions/runs/14342826037 seems like the ubuntu 20.04 runners are being removed.
```
This is a scheduled Ubuntu 20.04 brownout. Ubuntu 20.04 LTS runner will be removed on 2025-04-15.
For more details, see https://github.com/actions/runner-images/issues/11101
```
failed here:
- https://github.com/kubernetes/kubeadm/issues/3179

support-command.yaml: switch to 24.04 ubuntu

---

kinder/ci/tools/update-workflows/templates/workflows/encryption-algorithm-tasks.yaml
kinder/ci/workflows/encryption-algorithm-tasks.yaml

Update the encryption algorithm from ECDSA-P256 to ECDSA-P384 for tasks used in encryption-algorithm-latest CI flow.
Corresponding changes went in  https://github.com/kubernetes/kubernetes/pull/131677

ci(kinder): Upgrade encryption algorithm to ECDSA-P384

---

kinder/cmd/kinder/version/version.go
kinder/pkg/constants/constants.go

kinder has been used for kubeadm e2e tests for many releases, but its version remained 0.x. Update the version to v1.0.0 to identify its stability.

kinder: update version to v1.0.0

---

kinder/ci/tools/update-workflows/templates/workflows/instance-config-tasks.yaml
kinder/ci/workflows/instance-config-tasks.yaml

Update the tests to:
* Disable the NodeLocalCRISocket feature gate and create a cluster.
* Disable the NodeLocalCRISocket feature gate and upgrade the cluster.
* Enable the NodeLocalCRISocket feature gate and upgrade the cluster.
Committing it for now, I'll review this again first tomorrow myself :)

Add beta stage test for NodeLocalCRISocket feature gate
