CHANGELOG.md
=> Move the CHANGELOG over here like all the other k8s repos

CHANGELOG.md
@mikedanese PTAL and merge, here are the release notes I aggregated for the third stable version of kubeadm
=> Add changelog items for the third version of kubeadm

docs/design/design.md
Fix the `pull` in docs/design/design.md
=> Fix typo in docs/design/design.md

docs/release-cycle.md
cc @kubernetes/sig-cluster-lifecycle-pr-reviews @kubernetes/kubernetes-release-managers 
Fixes: #252
=> Add a document with the processes of kubeadm development

docs/design/design_v1.8.md
=> fix borken link

docs/design/design_v1.8.md
=> fix typo in docs/design/design_v1.8.md

docs/design/design_v1.9.md
Create the placeholder for design doc v1.9.
By having this placeholder already in place, it will be easier to spot differences/review the upcoming PR with the changes to this document
=> Create design doc v1.9 placeholder

tests/e2e/pinned_rpms.sh
=> add rpms script

docs/design/design_v1.10.md
This is a copy of the v1.9 doc.
=> Add v1.10 design doc

docs/test-failures.md
Provide guidance on where to look for common failure cases for kubeadm
=> Update troubleshooting for create cluster failure

docs/test-failures.md
Followup cleanup from PR https://github.com/kubernetes/kubeadm/pull/704
/cc @roberthbailey @xiangpengzhao
=> Cleanup formatting in test-failures.md

docs/design/design_v1.10.md, docs/design/design_v1.9.md
=> fix grammar mistake

docs/design/design_v1.9.md
=> Typo fix in design_v1.9.md

docs/design/design_v1.10.md, docs/design/design_v1.8.md, docs/design/design_v1.9.md
Corrected all the duplicated word "the the" in this project.
=> some typo fixes

docs/design/design_v1.8.md, docs/design/design_v1.9.md
does not exists->does not exist
=> Typo fix: does not exists->does not exist

docs/design/design_v1.10.md, docs/design/design_v1.8.md, docs/design/design_v1.9.md
=> Typo fix: boostrap->bootstrap

docs/design/design_v1.10.md, docs/design/design_v1.9.md
=> Add certified-k8s logo for 1.10 and fix broken link for 1.9

docs/design/design_v1.8.md
Line 131: recognise->recognize
=> Typo fix: recognise->recognize

CONTRIBUTING.md
=> contributing.md: add notes about website docs and unit tests

SECURITY_CONTACTS
close #855
cc @luxas @timothysc @fabriziopandini @jessfraz
Signed-off-by: Xianglin Gao <xianglin.gxl@alibaba-inc.com>
=> add SECURITY_CONTACTS file

vagrant/hack/ansible/group_vars/all/main.yml
Line 13: kubernets->kubernetes
=> Typo fix: kubernets->kubernetes

docs/design/design_v1.10.md
`—features-gates=self-hosting` -> `--features-gates=SelfHosting`
=> Fix self-hosting flag

vagrant/hack/ansible/group_vars/all/main.yml
=> add a note

vagrant/hack/lib/cluster_api.py
Fix some typos in messages:
line 170: does not exists->does not exist
line 222: compability->compatibility
=> Fix some typos in messages

testing-pre-releases.md
Signed-off-by: Rui Cao <ruicao@alauda.io>
=> Fix wrong link

docs/managing-e2e-tests.md
@kubernetes/sig-cluster-lifecycle-pr-reviews 
long have we waited...
pls, let me know if you find bad phrases or typos or if you think something can be organized better.
fixes https://github.com/kubernetes/kubeadm/issues/868
UPDATE1: fixed typos and did some copy edits.
UPDATE2: addressed feedback from Fabrizio.
UPDATE3: addressed feedback from Peter.
UPDATE4: added video URL for the 1.11 cycle
=> add doc about managing e2e tests

OWNERS
adding self to reviewers list.
followup from the other PR for `k/k`.
https://github.com/kubernetes/kubernetes/pull/69166
thanks.
/kind cleanup
/assign @timothysc
=> OWNERS: add neolit123 to reviewers

docs/design/design_v1.10.md, docs/design/design_v1.8.md, docs/design/design_v1.9.md
=> Fix the wrong file name

testing-pre-releases.md, vagrant/README.md
Delete the redundant word ‘the’
=> Delete the redundant word

docs/managing-e2e-tests.md
Delete the redundant word ‘the’
=> Delete the redundant word ‘the’

OWNERS
Add myself as approver to be able to approve PRs in this repo.
Also focus on the work that is to be done under /tests/e2e
with the transition to kind for testing.
=> OWNERS: add neolit123 to approvers

tests/e2e/packages/README.md, tests/e2e/packages/verify_packages_install_deb.sh
- test CI/latest DEBs
- test all release DEBs from the support skew
/assign @timothysc @BenTheElder 
/area testing
/kind feature
/hold
test-infra PR: https://github.com/kubernetes/test-infra/pull/11215
=> add e2e test for install/uninstall DEB packages

kinder/pkg/test/workflow/taskCmdRunner.go
Temporary disable low-level task cancel to better understand test infra error
/kind feature
=> Temporary disable cancel task

kinder/cmd/kinder/create/cluster/createcluster.go, kinder/pkg/actions/util.go
=> kinder: enable Calico instead of WeaveNet

kinder/ci/workflows/upgrade-stable-master.yaml
This PR copy/paste typo into upgrade stable-to-master
=> fix-upgrade-stable-to-master

kinder/pkg/test/workflow/workflow.go
This PR adds support for including workflow
This enables the reuse of the same list of task in several workflows (as an alternative to make workflows configurable via env variables)
=> kinder: add support for include workflow

README.md
As someone first heard about it, start from a defnition would be more friendly. Add definition about kubeadm to make things clear.
Add kubeadm cmdlets
Add kubeadm cmdlets so that readers can have a general concept about what do kubeadm cover so far.
change format
change format
Update the pull request and signed CLA
Update the pull request and signed CLA
Simplify the sample cmdlet here
Simplify the sample cmdlet here so that it won't distract the readers. Keep it brief as requested
Refine the definition
update definition
update definition as requested
Update as requested
=> Add definition about kubeadm ( finally squash modifications with success ) thanks :)

kinder/pkg/actions/cluster-info.go
This should fix kubeadm-kinder-upgrade-1.12-1.13 failing test
=> kinder: fix cluster-info

docs/design/design_v1.10.md
=> Delete redundant "extra"

docs/managing-e2e-tests.md
make the document `docs/managing-e2e-tests.md` more up-to-date after using kind/kinder and the gce job removal.
include some extra info about release blocking jobs and email alerts.
=> update the document about updating test-infra jobs

kinder/pkg/actions/kubeadm-upgrade.go
This PR fixes kinder upgrades for HA cluster - when working with pre-releases versions
More specifically it guarantees that the images are pre-loaded on all the control-plane nodes before running kubeadm upgrade apply, so everything will be in place when kubeadm creates pre-pull DaemonSets (otherwise we will be stuck because of pre-releases version are not published on the default K8s image registry)
/kind bug
=> kinder: fix multi node upgrades

tests/e2e/kind/ha-cp/ha-cp.yaml
change kind-master job (and possibly kind-1.14) to test HA
refs https://github.com/kubernetes/kubeadm/issues/1567
=> change kind-master job to test HA

kinder/ci/kubeadm-periodic.tests.md
This PR documents periodic tests implemented with kind
/assign @ereslibre
=> improve periodic test doc

tests/e2e/kind/ha-cp/ha-cp.yaml, tests/e2e/kind/single-cp/single-cp.yaml
/kind bug
/priority critical-urgent
=> kind: move the configs to Cluster/v1alpha3

kinder/pkg/actions/waiter.go
This PR introduces a workaround for reducing flakes from the upgrade test.
However, the real source of the problems still is not clear and should be investigated
/kind flake
=> fix-upgrade-flake

kinder/README.md, kinder/doc/kind-kinder.md, kinder/roadmap.md
As per slack discussion, this PR documents differences between kind & kinder & add a curated list with all the great stuff that kinder is using from kind
/cc @neolit123 
/cc @BenTheElder
=> kind & kinder

CONTRIBUTING.md
Fix broken link for `testing-pre-releases.md` in CONTRIBUTING.md.
=> contributing.md: fix broken link for testing-pre-releases.md

kinder/cmd/kinder/do/do.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> cleanup: correct misspelled words in help message

kinder/pkg/cluster/status/node.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> cleanup typos in node.go

kinder/pkg/cri/confighelper.go
=> fix wrong spells in confighelper.go

kinder/pkg/extract/extract.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> cleanup typos in extract.go

kinder/third_party/kind/readme.md
=> fix typo in readme.md

kinder/pkg/cri/containerd/createhelper.go
=> fix mis-spelling in createhelper.go

kinder/cmd/kinder/create/cluster/createcluster.go, kinder/pkg/cluster/manager/create.go, kinder/pkg/config/config.go, kinder/third_party/kind/config/defaults.go, kinder/third_party/kind/config/readme.md, kinder/third_party/kind/config/validate.go, kinder/third_party/kind/config/validate_test.go
@fabriziopandini it's OK for this PR to wait for your other work in kinder right now.
it's a POC more or less, but it think it's doing the right thing.
(commits have messages)
=> kinder: use only the public kind config and wrap it

docs/updating-command-reference.md
=> fix mis-spelling in updating-command-reference.md

kinder/pkg/cri/docker/createhelper.go
Signed-off-by: Sakura <longfei.shang@daocloud.io>
=> fir typo "deamon" -> "daemon"

kinder/pkg/cri/docker/createhelper.go
=> cleanup: fix mis-spelling in createhelper.go

kinder/pkg/cluster/manager/actions/waiter.go
This PR tries to improve the current workaround for RBAC flakiness during upgrades
=> kinder: workaround RBAC flakiness  during upgrades

kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go
=> fix e2e kustomize test

kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go
:blush:
:sweat_smile:
/assing @neolit123
=> fix-e2e-kustomize-bis

kinder/README.md
First attempt to contribute. Hope it helps!
=> improves kinder readme

OWNERS
add @yastij as kubeadm reviewer, please `lgtm`
/kind cleanup
/hold
=> updade OWNERS for 1.16

kinder/pkg/cluster/manager/actions/kubeadm-config.go, kinder/pkg/cri/docker/createhelper.go
=> Correct word misspelling

tests/e2e/manifests/verify_manifest_lists.sh
- fix env. var name
- call `go mod init` on each execution to get latest api-machniery
- cleanup go.{mod|sum} on exit
/assign @yagonobre @yastij 
fixes https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-all#periodic-manifest-lists
=> tests/e2e/manifests: fix correct usage of go modules

kinder/ci/kubeadm-periodic.tests.md, kinder/ci/workflows/discovery-1.16.yaml, kinder/ci/workflows/discovery-tasks.yaml, kinder/ci/workflows/kustomize-1.16.yaml, kinder/ci/workflows/kustomize-tasks.yaml
/sig cluster-lifecycle
/area testing
/priority importan-soon
=> add 1.16 jobs for discovery and kustomize

kinder/pkg/extract/extract.go
/assign @neolit123 
/area testing
/area kinder
/priority critical-urgent
=> kinder: fix flakiness due to delay on publishing artifacts

kinder/pkg/cluster/manager/actions/kubeadm-init.go
=> kinder: fix-calico

kinder/pkg/cluster/manager/actions/cluster-info.go, kinder/pkg/constants/constants.go
Fixes https://github.com/kubernetes/kubeadm/issues/1864
=> fix E2E upgrade 1.16 master failures

operator/controllers/runtimetask_reconcile.go, operator/controllers/runtimetaskgroup_controller.go, operator/controllers/util.go
This PR implements the task group controller
NB. I'm splitting operator implementation in a series of PRs to make things easier to review, but the backside of this is that there are some TODO's, that will be addressed in follow up PRs when all the operators will be in places.
If this can help. we can arrange for a shared PR review
/kind feature
/sig cluster-lifecycle
/area kubeadm-operator
/priority important-soon
/cc @neolit123
/cc @ereslibre
/cc @yagonobre
/cc @yastij
=> kubeadm-operator: implement the taskgroup controller

CONTRIBUTING.md
=> CONTRIBUTING.md: add onboarding video link

kinder/ci/workflows/external-etcd.yaml, kinder/ci/workflows/kustomize-tasks.yaml, kinder/ci/workflows/regular-tasks.yaml, kinder/ci/workflows/skew-x-on-y-tasks-automatic-copy-certs.yaml, kinder/ci/workflows/skew-x-on-y-tasks.yaml, kinder/ci/workflows/upgrade-tasks-automatic-copy-certs.yaml, kinder/ci/workflows/upgrade-tasks.yaml
commits:
```
kinder: add --loglevel=debug to tasks that are mnissing it
kinder: adjust report prefixes
kinder: adjust comments related to copy-certs workflows
```
=> kinder: add --loglevel=debug to tasks that are mnissing it

kinder/cmd/kinder/kinder.go, kinder/doc/kind-kinder.md, kinder/pkg/cluster/manager/create.go
Little cleanup trying to make easier future upgrades of the kind release
=> kinder: remove "sigs.k8s.io/kind/pkg/log" dependency

operator/Dockerfile, operator/commands/exec.go, operator/commands/factory.go, operator/commands/kubeadm_renew_certificate.go, operator/commands/kubeadm_upgrade_apply.go, operator/commands/kubeadm_upgrade_node.go, operator/commands/kubectl_drain.go, operator/commands/kubectl_uncordon.go, operator/commands/preflight.go, operator/commands/upgrade_kubeadm.go, operator/commands/upgrade_kubectlkubelet.go, operator/controllers/runtimetask_controller.go, operator/controllers/runtimetaskgroup_controller.go, operator/controllers/util.go, operator/main.go
This PR implements the task controller
NB. I'm splitting operator implementation in a series of PRs to make things easier to review, but the backside of this is that there are some TODO's, that will be addressed in follow up PRs when all the operators will be in places.
If this can help. we can arrange for a shared PR review
/kind feature
/sig cluster-lifecycle
/area kubeadm-operator
/priority important-soon
/cc @neolit123
/cc @ereslibre
/cc @yagonobre
/cc @yastij
=> kubeadm-operator: implement the task controller

kinder/pkg/cluster/status/node.go
=> kinder: stop caching kubeadmVersion

kinder/pkg/cluster/manager/actions/cluster-info.go
"etcdctl version" is not portable to 3.3.x.
Looks like the download instructions are wrong too:
https://github.com/etcd-io/etcd/releases/tag/v3.3.17
etcdctl 3.3.x uses "--version" and 3.4.x uses "version".
To not a have a chicken and egg problem get the version
from the etcd binary which is consistent across 3.3.x and 3.4.x -
uses "--version".
=> kinder: get the etcdctl version from the etcd binary

kinder/cmd/kinder/test/e2e/e2e.go, kinder/cmd/kinder/test/e2ekubeadm/e2ekubeadm.go, kinder/pkg/cluster/manager/create.go, kinder/pkg/cluster/manager/manage.go, kinder/pkg/cluster/status/cluster.go
Little cleanup trying to make easier future upgrades of the kind release
=> Kinder: Remove "sigs.k8s.io/kind/pkg/cluster" dependency

kinder/cmd/kinder/get/clusters/clusters.go, kinder/cmd/kinder/get/get.go
=> kinder: remove kind clusters dependencies

CONTRIBUTING.md, docs/managing-e2e-tests.md, docs/testing-pre-releases.md
Fixes#1921
kubeadm\docs\design\design_v1.8.md https://raw.githubusercontent.com/cncf/artwork/master/kubernetes/certified-kubernetes/1.8/color/certified-kubernetes-1.8-color.png
ubeadm\docs\design\design_v1.9.md https://raw.githubusercontent.com/cncf/artwork/master/kubernetes/certified-kubernetes/1.9/color/certified-kubernetes-1.9-color.png
the two files i don't know how to fix them.
=> fix some 404 urls

operator/controllers/runtimetaskgroup_controller_test.go
Ref: #1920
/cc @fabriziopandini
=> kubeadm operator: add unit tests for runtimetaskgroup_controller

operator/controllers/runtimetaskgroup_reconcile_test.go
Ref: #1920
/cc @fabriziopandini
=> kubeadm operator: add unit tests for runtimetaskgroup_reconcile

operator/controllers/runtimetaskgroup_reconcile_test.go
Ref: #1920 #1919
/cc @fabriziopandini
=> kubeadm operator: rename function name in runtimetaskgroup_reconcile_test.go

operator/controllers/runtimetask_controller.go, operator/controllers/runtimetask_controller_test.go, operator/controllers/runtimetask_reconcile_test.go
This PR adds the first set of unit test for the kubeadm operator
=> kubeadm operator: add unit test tests - part1

kinder/doc/kind-kinder.md, kinder/roadmap.md
Small updates to kinder roadmap and docs
/area kinder
/milestone next
=> kinder: roadmap update

kinder/pkg/cluster/status/node.go
Fix an error in kinder WriteFile
=> kinder: fix WriteFile

docs/design/design_v1.8.md, docs/design/design_v1.9.md
=> two pic err

kinder/pkg/cluster/manager/actions/kubeadm-init.go, kinder/pkg/cluster/manager/actions/kubeadm-join.go, kinder/pkg/constants/constants.go
scope down the list of ignored preflight errors.
=> kinder: use a short list of ignored preflight errors

operator/controllers/runtimetask_reconcile.go, operator/controllers/runtimetaskgroup_reconcile.go
Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>
=> Fix a typo 'the the' -> 'the'

docs/release-cycle.md
fixes https://github.com/kubernetes/kubeadm/issues/1766
- tried to use the original doc but iterate on some of the aspects that have changed.
- amended the indentation so the diff should be smaller otherwise.
=> docs/release-cycle.md: update the document

kinder/pkg/cluster/status/node.go
This is a temporary fix for https://github.com/kubernetes/kubeadm/issues/1918
=> Kinder: Temporarily disable clustersettings

CONTRIBUTING.md
=> CONTRIBUTING.md: add 101 video

kinder/cmd/kinder/cp/cp.go, kinder/cmd/kinder/do/do.go, kinder/cmd/kinder/exec/exec.go, kinder/doc/reference.md
Although it is spelling mistakes, it might make an affects while reading.
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
=> Remove duplicated words

kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go
- Upgrade node kubelet and kubectl last, after the kubeadm binary
is upgraded and after the "kubeadm upgrade" process has finished
on all nodes.
see
https://github.com/kubernetes/kubernetes/issues/86676
https://github.com/kubernetes/kubeadm/issues/1981
deciding on how to proceed here, after https://github.com/kubernetes/kubernetes/issues/86676 sees more discussion.
=> kinder: upgrade node's kubelet and kubectl last

kinder/cmd/kinder/kinder.go, kinder/pkg/cluster/status/node.go
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>
=> Fix some typos in comments

docs/release-cycle.md
Fix some typos in release-cycle.md.
1: Go trough -> Go through
2: minium -> minimum
=> Fix some typos in release-cycle.md

kinder/doc/kind-kinder.md
Although it is spelling mistakes, it might make affects while reading.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>
=> docs: Fix some typos

docs/testing-pre-releases.md
Fix simple typo in testing-pre-releases.md (binariess -> binaries)
=> Fix simple typo in testing-pre-releases.md

kinder/ci/workflows/discovery-1.18.yaml, kinder/ci/workflows/external-etcd-1.18.yaml, kinder/ci/workflows/kustomize-1.18.yaml, kinder/ci/workflows/regular-1.18.yaml, kinder/ci/workflows/skew-1.18-on-1.17.yaml, kinder/ci/workflows/skew-master-on-1.18.yaml, kinder/ci/workflows/upgrade-1.17-1.18.yaml, kinder/ci/workflows/upgrade-1.18-master.yaml
xref https://github.com/kubernetes/kubeadm/issues/1963
test-infra PR:
https://github.com/kubernetes/test-infra/pull/16527
=> kinder: add test workflows for 1.18

kinder/cmd/kinder/version/version.go
remove dependency from kind/version package
=> [kinder] remove dependency kind version

kinder/pkg/cluster/manager/create.go
this PR remove a left-over dependency to "k8s.io/kubeadm/kinder/pkg/exec"
=> [kinder] remove dependency kind exec

kinder/pkg/cluster/manager/actions/kubeadm-init.go, kinder/pkg/cluster/manager/actions/kubeadm-join.go, kinder/pkg/constants/constants.go
Drops support for v1.1r4 from kinder. 
=> [kinder] drop support for v1.14 from kinder

kinder/doc/kind-kinder.md, kinder/pkg/cluster/manager/create.go
this PR removes another kind dependency
/area kinder
=> remove dependency kind concurrent

docs/managing-e2e-tests.md
Looks like the youtube video has been made private.
=> Removing a dead link

kinder/cmd/kinder/build/nodevariant/nodevariant.go, kinder/pkg/build/alter/alter.go
=> [kinder] add --with-kubeadm-additional-images option to kinder build node-image-variant

kinder/cmd/kinder/build/nodevariant/nodevariant.go, kinder/pkg/build/alter/alter.go, kinder/pkg/build/bits/pathBits.go, kinder/pkg/extract/extract.go
=> add --with-path option to kinder build node-image-variant

kinder/pkg/cri/containerd/alterhelper.go
This PR fixes extra-images pre-load for containerd. 
As a result during init I get:
```
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
I0613 13:01:22.404308     174 checks.go:838] image exists: k8s.gcr.io/kube-apiserver:v1.18.2
I0613 13:01:22.411883     174 checks.go:838] image exists: k8s.gcr.io/kube-controller-manager:v1.18.2
I0613 13:01:22.422184     174 checks.go:838] image exists: k8s.gcr.io/kube-scheduler:v1.18.2
I0613 13:01:22.429465     174 checks.go:838] image exists: k8s.gcr.io/kube-proxy:v1.18.2
I0613 13:01:22.436521     174 checks.go:838] image exists: k8s.gcr.io/pause:3.2
I0613 13:01:22.444462     174 checks.go:838] image exists: k8s.gcr.io/etcd:3.4.3-0
I0613 13:01:22.455687     174 checks.go:838] image exists: …
```
=> fix extra images pre-load for containerd

docs/ha-considerations.md
Missing code for the health check script file used by the `keepalived` configuration. 
fixes https://github.com/kubernetes/kubeadm/issues/2189
=> Issue #2189 - missing keepalived health check script file.

kinder/ci/workflows/discovery-1.19.yaml, kinder/ci/workflows/external-etcd-1.19.yaml, kinder/ci/workflows/kustomize-1.19.yaml, kinder/ci/workflows/regular-1.19.yaml, kinder/ci/workflows/skew-1.19-on-1.18.yaml, kinder/ci/workflows/skew-master-on-1.19.yaml, kinder/ci/workflows/upgrade-1.18-1.19.yaml, kinder/ci/workflows/upgrade-1.19-master.yaml
xref https://github.com/kubernetes/kubeadm/issues/2076
test infra PR: https://github.com/kubernetes/test-infra/pull/17329
=> kinder: add test workflows for 1.19

kinder/pkg/cluster/status/node.go
in pkg/cluster/status#WriteNodeSettings(), wrap the
calls to mkdir and WriteFile in a PollImmediate with 1 second
interval and 20 seconds timeout.
This is done with the idea to retry on flakes during cluster
creation when the commands can return "exit status 1", for
unknown reasons.
xref https://github.com/kubernetes/kubeadm/issues/1918
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-master/1289769800460931073/artifacts/task-02-create-cluster-log.txt
> time="04:01:28" level=error msg="failed to write /kinder/node-settings.yaml: exit status 1"
> Error: failed to create cluster: failed to write /kinder/node-settings.yaml: exit status 1
=> kinder: retry writing node-settings.yaml

tests/e2e/packages/verify_packages_published.sh
This line should be rpm package not deb package
=> fix wrong comment

README.md
follow up from this PR to squash the commits:
https://github.com/kubernetes/kubeadm/pull/2239
=> Add links to relevant docs to README (followup)

kinder/ci/kubeadm-periodic.tests.md
- Add note that some features are not tested trough the whole skew.
- Remove the tables in the file and show names with wildcards instead.
- Apply other minor adjustments.
discussion here:
https://github.com/kubernetes/kubeadm/pull/2298/files#r494197913
=> kinder/ci/kubeadm-periodic.tests.md: remove tables

docs/managing-e2e-tests.md, kinder/ci/kubeadm-periodic.tests.md, kinder/ci/workflows/discovery-latest.yaml, kinder/ci/workflows/external-etcd-latest.yaml, kinder/ci/workflows/patches-latest.yaml, kinder/ci/workflows/presubmit-upgrade-latest.yaml, kinder/ci/workflows/regular-latest.yaml, kinder/ci/workflows/skew-latest-on-1.19.yaml, kinder/ci/workflows/upgrade-1.19-latest.yaml, kinder/ci/workflows/upgrade-latest-no-addon-config-maps.yaml
Ref: #2302
XRef: kubernetes/test-infra#19381
TODO: Remove the old configuration after kubernetes/test-infra#19381 merged.
=> Step1: Remove offensive words from CI jobs configuration

kinder/ci/workflows/discovery-1.20.yaml, kinder/ci/workflows/external-etcd-1.20.yaml, kinder/ci/workflows/regular-1.20.yaml, kinder/ci/workflows/skew-1.20-on-1.19.yaml, kinder/ci/workflows/skew-latest-on-1.20.yaml, kinder/ci/workflows/upgrade-1.19-1.20.yaml, kinder/ci/workflows/upgrade-1.20-latest.yaml
xref https://github.com/kubernetes/kubeadm/issues/2277
test infra PR: https://github.com/kubernetes/test-infra/pull/19852
=> kinder: add test workflows for 1.20

tests/e2e/manifests/verify_manifest_lists.sh
=> Remove useless cleanup code since src dir never existed

tests/e2e/manifests/verify_manifest_lists.sh
=> Cleanup tmp file introduced during test

tests/e2e/manifests/verify_manifest_lists.go
new coredns image is located at a coredns subpath.
fixes these failures:
https://testgrid.k8s.io/sig-cluster-lifecycle-all#periodic-manifest-lists
=> tests/e2e/manifests: adapt to recent coredns image change

OWNERS
sync the k/kubeadm OWNERS with k/k/cmd/kubeadm:
https://github.com/kubernetes/kubernetes/pull/98547
https://github.com/neolit123/kubernetes/blob/afea70f9aeec8166422851f8290d9f18166f682e/cmd/kubeadm/OWNERS
=> sync OWNERS with k/k

CONTRIBUTING.md
=> contributing.md: fix wrong URL

kinder/ci/workflows/discovery-1.21.yaml, kinder/ci/workflows/external-ca-1.21.yaml, kinder/ci/workflows/external-etcd-1.21.yaml, kinder/ci/workflows/patches-1.21.yaml, kinder/ci/workflows/regular-1.21.yaml, kinder/ci/workflows/skew-1.21-on-1.20.yaml, kinder/ci/workflows/skew-kubelet-1.19-on-1.21.yaml, kinder/ci/workflows/skew-kubelet-1.20-on-1.21.yaml, kinder/ci/workflows/skew-kubelet-1.21-on-latest.yaml, kinder/ci/workflows/skew-latest-on-1.21.yaml, kinder/ci/workflows/upgrade-1.20-1.21.yaml, kinder/ci/workflows/upgrade-1.21-latest.yaml
xref https://github.com/kubernetes/kubeadm/issues/2362
test infra PR: https://github.com/kubernetes/test-infra/pull/21643
=> kinder: add test workflows for 1.21

kinder/doc/e2e-test.md, kinder/doc/reference.md
delete redundant control characters
=> delete redundant control characters

tests/e2e/manifests/verify_manifest_lists.sh
Signed-off-by: Ma Xinjian <maxj.fnst@fujitsu.com>
=> use a scoped tempdir instead of /tmp

docs/ha-considerations.md
Fixes: #2478 
With the new image(`osixia/keepalived:2.0.17`), `keepalived` seems to work properly:
```sh
*** CONTAINER_LOG_LEVEL = 3 (info)
*** Search service in CONTAINER_SERVICE_DIR = /container/service :
*** link /container/service/keepalived/startup.sh to /container/run/startup/keepalived
*** link /container/service/keepalived/process.sh to /container/run/process/keepalived/run
*** link /container/service/keepalived/finish.sh to /container/run/process/keepalived/finish
*** Set environment for startup files
*** Environment files will be proccessed in this order :
Caution: previously defined variables will not be overriden.
/container/environment/99-default/default.yaml
To see how this files are processed and environment variables values,
run this container with '--loglevel debug'
*** …
```
=> docs: fix the bug that keepalived image missing curl

kinder/ci/tools/update-workflows/pkg/run.go
Signed-off-by: Ma Xinjian <maxj.fnst@fujitsu.com>
=> Fix small typo

kinder/cmd/kinder/do/do.go, kinder/pkg/cluster/manager/actions/actions.go, kinder/pkg/cluster/manager/actions/kubeadm-config.go, kinder/pkg/cluster/manager/actions/kubeadm-init.go, kinder/pkg/cluster/manager/actions/kubeadm-join.go, kinder/pkg/cri/nodes/confighelper.go, kinder/pkg/kubeadm/automaticcopycertspatch.go, kinder/pkg/kubeadm/config.go, kinder/pkg/kubeadm/discovery.go, kinder/pkg/kubeadm/dockerpatch.go, kinder/pkg/kubeadm/externaletcdpatch.go, kinder/pkg/kubeadm/kubednspatch.go
kinder: add flag for forcing the kubeadm config version
Ref: #2428 
Fixes: #2249
=> kinder: add flag for forcing the kubeadm config version

.github/ISSUE_TEMPLATE.md, README.md
since we are getting support tickets occasionally here, let's make it clearer in the readme and issue template that we keep this repository for feature / bug tracking only. we can still keep some `kind/support` tickets open, if we suspect there is a bug.
update the issue template to:
- include up-to-date links to the TS guide
- link to the support channels
- remove the "Is this a request for help?" question
update the README.md:
- stating that this issue tracker is not for support
- link to the support channels
- include up-to-date links to the TS guide
- add some more documentation links
=> update the issue template and README.md about support

kinder/pkg/cri/nodes/common/util.go
=> bug: failed to create cluster with proxy

kinder/pkg/cluster/manager/actions/kubeadm-init.go
Make sure that for single node clusters only a specific taint
is removed for kubeadm version <1.24 or >=1.24.
Add TODOs for future versions.
xref https://github.com/kubernetes/kubeadm/issues/2200
=> kinder: handle the "master" taint changes for 1.24

kinder/pkg/cluster/manager/create.go, kinder/pkg/cluster/status/node.go
there are still some flakes in the kinder jobs:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-1-21
```
time="15:56:56" level=debug msg="Writing node settings at /kinder/node-settings.yaml (attempt 22)..."
time="15:56:56" level=debug msg="Running: [docker exec kinder-regular-control-plane-1 mkdir -p /kinder]"
...
Error: failed to create cluster: failed to create directory /kinder: exit status 1
time="15:57:00" level=error msg="failed to create directory /kinder: exit status 1"
exit status 1
```
Kinder node containers are started in parallel.
In some cases trying to write settings to the nodes
right after that (via e.g. mkdir -p /kinder ...) can fail,
without a definitive reason. Also this is not reproducible
locally it seems, so perhaps it happens in CI …
=> kinder: wait for node containers to start

kinder/pkg/cluster/status/node.go, kinder/pkg/exec/host-cmd.go, kinder/pkg/exec/node-cmd.go
Error messages need to show the values that are incorrect in order to
make sense of them!
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
=> status: improve error messages

docs/testing-pre-releases.md
=> fix error link url

kinder/ci/tools/update-workflows/templates/workflows/presubmit-upgrade-latest.yaml, kinder/ci/workflows/presubmit-upgrade-latest.yaml, kinder/pkg/cluster/manager/actions/kubeadm-init.go, kinder/pkg/cri/nodes/common/util.go, kinder/pkg/exec/node-cmd.go
=> update go format

README.md, docs/managing-e2e-tests.md, docs/release-cycle.md, docs/test-failures.md, docs/testing-pre-releases.md, docs/updating-command-reference.md
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
When I read the documentation, I found some syntax errors, and this pr fixes these errors in hopes of helping the community
=> Optimize the document for readability

docs/testing-pre-releases.md
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
Optimize the document by reformat table and fix item numbering
The following pictures show the modified content for the convenience of review
=> Optimize the document by reformat table

kinder/hack/orderimports/orderimports.go, kinder/hack/orderimports/orderimports_test.go
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
=> Clean up excess unprocessed parameters

kinder/ci/tools/update-workflows/templates/workflows/patches-tasks.yaml, kinder/ci/workflows/patches-tasks.yaml
Ref: https://github.com/kubernetes/kubernetes/pull/115575
=> Patches e2e: add checking logic for kube-system/kubelet-config ConfigMap

docs/ha-considerations.md
Replace error: [export VIP=192.168.0.40']  with: [export VIP=192.168.0…40]
=> Replace error: [export VIP=192.168.0.40'] 

tests/e2e/manifests/verify_manifest_lists.go
This PR introduces a map called `architecturesToRemove` to `verify_manifest_list.go`, which maps the first unsupported version of Kubernetes to a list of architectures that should be removed. In the function `verifyManifestList`, the unsupported architectures are removed from the architecture list based on the Kubernetes version provided. This ensures that only supported architectures are considered during verification.
/kind bug
ref: https://github.com/kubernetes/kubeadm/issues/2873
=> fix: Add support for removing unsupported architectures 

kinder/pkg/cluster/manager/actions/actions.go, kinder/pkg/cluster/manager/actions/kubeadm-config.go, kinder/pkg/cluster/manager/actions/kubeadm-upgrade.go
=> Fix a bug in UpgradeAddonsBeforeControlPlane feature gate e2e test

OWNERS
ref https://github.com/kubernetes/kubernetes/pull/118341
=> add pacoxu to approvers

OWNERS
so that I can auto-assigned if there is any changes need to be reviewed.
=> Add chendave to reviewer list

kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-addons.yaml, kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-discovery.yaml, kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-dryrun.yaml, kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-external-ca.yaml, kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-external-etcd.yaml, kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-kubelet-x-on-y.yaml, kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-learner-mode.yaml, kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-patches.yaml, kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-rootless.yaml, kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-upgrade-addons-before-controlplane.yaml, kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-upgrade.yaml, kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder-x-on-y.yaml, kinder/ci/tools/update-workflows/templates/testinfra/kubeadm-kinder.yaml
xref https://github.com/kubernetes/kubeadm/issues/2894
TODO: test infra pr
=> kinder: use eks cluster in test-infra jobs

kinder/cmd/kinder/build/build.go
Add detailed usage of `build` command.
=> kinder: update the usage of build command

docs/design/design_v1.10.md, docs/design/design_v1.7.md, docs/design/design_v1.8.md, docs/design/design_v1.9.md
fixed broke link.
fixes: #2975
=> fixed broken links in documents under design

kinder/pkg/cluster/manager/create.go
Running docker commands in parallel has proven to confuse the docker CR on the host and cause random failures. Also it is less clear what container command failed exactly.
Make the whole node creation linear. This will inevitably make the kinder cluster creation slower, but will reduce the change for unexplainable flakes and allow us to debug and potentially retry certain commands that are flaky.
In the past one such command was a simple:
"docker exec ... mkdir ..."
=> kinder: remove parallel code during node creation

kinder/pkg/cluster/manager/actions/waiter.go
While triaging your project, our bug fixing tool generated the following message-
> In File: [waiter.go](https://github.com/kubernetes/kubeadm/blob/main/kinder/pkg/cluster/manager/actions/waiter.go#L154), Line: 154: `pass <- true`. In function `waitFor`, there is a send operation. But no matching receive operation is found on that channel from any other goroutine.
After manual triaging, we found out that the go routine inside the `waitFor` method is sending to the `pass` channel. And the polling loop inside the `waitFor` method is receiving from the channel. We also noted that there's a `timer` inside the `select` block that returns False if the timeout occurs.
It all seems correct, except a corner case such as-
The receive from `pass` and the `timer.C` occurs at the same time. In that …
=> Fixed Concurrency Issue: channel communication of kinder

kinder/ci/tools/update-workflows/templates/workflows/patches-tasks.yaml, kinder/ci/workflows/patches-tasks.yaml
Reverts kubernetes/kubeadm#2825
Ref: https://github.com/kubernetes/kubeadm/issues/3008
=> Revert "Patches e2e: add checking logic for kube-system/kubelet-config ConfigMap"

kinder/pkg/kubeadm/config.go
See https://github.com/kubernetes/kubernetes/issues/123804#issuecomment-1985428951
/cc @neolit123
=> Remove --enable-hostpath-provisioner option

OWNERS
/cc @pacoxu @neolit123 
https://github.com/kubernetes/kubernetes/pull/125096
=> add carlory as reviewer

OWNERS
sync for https://github.com/kubernetes/kubernetes/pull/129250
/hold 
until https://github.com/kubernetes/kubernetes/pull/129250 is merged.
=> kubeadm: update owners for v1.33

OWNERS
Follow: https://github.com/kubernetes/kubernetes/pull/131674, add HirazawaUi as approver for kubeadm.
=> add HirazawaUi to kubeadm approvers
